# SPDX-License-Identifier: MIT
"""Tests for tool_handlers (pre_tool_call inv-zen-004 gate + post_tool_call)."""

from __future__ import annotations

import os
from unittest.mock import patch

from hermes_plugins.hades.hooks.tool_handlers import (
    _FILE_EDIT_TOOLS,
    extract_commit_message,
    is_ai_attributed,
    post_tool_call,
    pre_tool_call,
)

                                                                             


def test_extract_commit_message_double_quoted():
    cmd = 'git commit -m "feat(foo): add bar"'
    assert extract_commit_message(cmd) == "feat(foo): add bar"


def test_extract_commit_message_single_quoted():
    cmd = "git commit -m 'fix(bar): correct baz'"
    assert extract_commit_message(cmd) == "fix(bar): correct baz"


def test_extract_commit_message_no_dash_m():
    cmd = "git commit"
    assert extract_commit_message(cmd) == ""


def test_extract_commit_message_with_escaped_quotes():
                                                            
    cmd = 'git commit -m "feat: \\"escaped\\" inside"'
    out = extract_commit_message(cmd)
                                                                            
    assert "feat:" in out


def test_extract_commit_message_non_string_input():
    """Defensive guard: non-string input (forward-compat for any future
    caller passing args directly) returns empty string without raising."""
    assert extract_commit_message(None) == ""
    assert extract_commit_message(12345) == ""
    assert extract_commit_message({"command": "git commit -m 'x'"}) == ""


                                                                               


def test_is_ai_attributed_co_authored_by_claude():
    assert is_ai_attributed("feat: x\n\nCo-Authored-By: prohibited assistant") is True


def test_is_ai_attributed_generated_with_ai():
    assert is_ai_attributed("fix: bar\n\nGenerated with prohibited assistant") is True


def test_is_ai_attributed_anthropic_keyword():
    assert is_ai_attributed("chore: anthropic-sourced change") is True


def test_is_ai_attributed_generated_by_claude():
    assert is_ai_attributed("feat: thing\n\nGenerated by prohibited assistant") is True


def test_is_ai_attributed_case_insensitive():
    assert is_ai_attributed("FEAT: X\n\nCO-AUTHORED-BY: CLAUDE") is True


def test_is_ai_attributed_clean_message():
    assert is_ai_attributed("feat(foo): add bar") is False


def test_is_ai_attributed_empty_string():
    assert is_ai_attributed("") is False


def test_is_ai_attributed_unrelated_mention():
                                                                             
                                                                   
    assert is_ai_attributed("feat: clauder is a name") is True


                                                                              


def test_pre_tool_call_returns_none_for_clean_commit():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": 'git commit -m "feat(foo): add bar"'},
            session_id="s1",
        )
    assert result is None


def test_pre_tool_call_returns_block_for_co_authored_by_claude():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": 'git commit -m "feat: x\n\nCo-Authored-By: prohibited assistant"'},
            session_id="s2",
        )
    assert isinstance(result, dict)
    assert result.get("action") == "block"
    assert "inv-zen-004" in result.get("message", "")


def test_pre_tool_call_returns_block_for_generated_with_ai():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": 'git commit -m "fix: y\n\nGenerated with prohibited assistant"'},
        )
    assert isinstance(result, dict)
    assert result["action"] == "block"


def test_pre_tool_call_returns_block_for_anthropic():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": 'git commit -m "chore: anthropic-sourced"'},
        )
    assert isinstance(result, dict)
    assert result["action"] == "block"


def test_pre_tool_call_returns_block_for_generated_by_claude():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": 'git commit -m "feat: z\n\nGenerated by prohibited assistant"'},
        )
    assert isinstance(result, dict)
    assert result["action"] == "block"


def test_pre_tool_call_skips_non_bash_tools():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Read",
            args={"file_path": "/foo/bar.txt"},
        )
    assert result is None


def test_pre_tool_call_skips_bash_without_git_commit():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": "echo 'co-authored-by: Claude'"},
        )
                                             
    assert result is None


def test_pre_tool_call_skips_git_commit_without_m_flag():
    """git commit without -m is interactive; we can't gate (no message yet)."""
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": "git commit"},
        )
    assert result is None


def test_pre_tool_call_handles_missing_args_gracefully():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(tool_name="Bash", args=None)
    assert result is None


def test_pre_tool_call_handles_non_dict_args():
    """If args isn't a dict (forward-compat with future Hermes signatures),
    callback must not raise."""
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(tool_name="Bash", args="not-a-dict")
    assert result is None


def test_pre_tool_call_handles_non_string_command():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = pre_tool_call(
            tool_name="Bash",
            args={"command": {"nested": "object"}},
        )
    assert result is None


                                                                               


def test_post_tool_call_returns_none():
    with patch.dict(os.environ, {"ZEN_HOOK_DRY_RUN": "1"}):
        result = post_tool_call(
            tool_name="Bash",
            args={"command": "ls"},
            result="ok",
            session_id="s1",
        )
    assert result is None


def test_post_tool_call_emits_file_edited_for_write_class_tools():
    """post_tool_call with write_file tool_name should emit a derived
    `file.edited` event in addition to `post_tool_call`. Payload field-set
    is documented contract: tool_name, args_summary, task_id, session_id,
    tool_call_id, hook_event_name, result_kind, result_size."""
    captured: list[tuple[str, dict]] = []

    def fake_invoke(event_name, payload):
        captured.append((event_name, payload))
        return 0

    with patch(
        "hermes_plugins.hades.hooks.tool_handlers.invoke_event_poster",
        side_effect=fake_invoke,
    ):
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop("ZEN_HOOK_DRY_RUN", None)
            post_tool_call(
                tool_name="write_file",
                args={"path": "/tmp/foo.txt", "content": "hi"},
                task_id="task-1",
                session_id="sess-1",
                tool_call_id="tc-1",
                result="written",
            )
    event_names = [e for e, _ in captured]
    assert "post_tool_call" in event_names
    assert "file.edited" in event_names

                                                                     
                                                                          
    post_payload = next(p for e, p in captured if e == "post_tool_call")
    assert post_payload["tool_name"] == "write_file"
    assert post_payload["task_id"] == "task-1"
    assert post_payload["session_id"] == "sess-1"
    assert post_payload["tool_call_id"] == "tc-1"
    assert post_payload["hook_event_name"] == "post_tool_call"
    assert "args_summary" in post_payload
    assert post_payload["result_kind"] == "str"
    assert post_payload["result_size"] == len("written")


def test_post_tool_call_no_file_edited_for_non_write_tools():
    captured_events: list[str] = []

    def fake_invoke(event_name, payload):
        captured_events.append(event_name)
        return 0

    with patch(
        "hermes_plugins.hades.hooks.tool_handlers.invoke_event_poster",
        side_effect=fake_invoke,
    ):
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop("ZEN_HOOK_DRY_RUN", None)
            post_tool_call(
                tool_name="terminal",
                args={"command": "ls"},
                result="...",
            )
    assert "post_tool_call" in captured_events
    assert "file.edited" not in captured_events


def test_file_edit_tools_includes_canonical_set():
    """File-edit tool set should at minimum include write_file + patch
    (Hermes canonical write-class tool names per disk-cleanup plugin
    inspection)."""
    assert "write_file" in _FILE_EDIT_TOOLS
    assert "patch" in _FILE_EDIT_TOOLS


def test_post_tool_call_result_size_handles_unsized_objects():
    """Defensive guard: results without __len__ (int, custom objects, None)
    must not raise; result_size falls back to -1."""
    captured_payloads: list[dict] = []

    def fake_invoke(event_name, payload):
        captured_payloads.append(payload)
        return 0

    with patch(
        "hermes_plugins.hades.hooks.tool_handlers.invoke_event_poster",
        side_effect=fake_invoke,
    ):
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop("ZEN_HOOK_DRY_RUN", None)
                                                                        
            post_tool_call(tool_name="Bash", args={}, result=42)
    assert len(captured_payloads) >= 1
    assert captured_payloads[0]["result_size"] == -1
    assert captured_payloads[0]["result_kind"] == "int"


                                                                             


def test_pre_tool_call_block_also_emits_blocked_audit_event():
    """When gate blocks, callback must emit pre_tool_call.blocked for audit
    trail BEFORE returning the block dict. Payload contract: reason='inv-zen-004'."""
    captured: list[tuple[str, dict]] = []

    def fake_invoke(event_name, payload):
        captured.append((event_name, payload))
        return 0

    with patch(
        "hermes_plugins.hades.hooks.tool_handlers.invoke_event_poster",
        side_effect=fake_invoke,
    ):
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop("ZEN_HOOK_DRY_RUN", None)
            result = pre_tool_call(
                tool_name="Bash",
                args={"command": 'git commit -m "feat: x\n\nCo-Authored-By: prohibited assistant"'},
                session_id="s1",
            )
    assert isinstance(result, dict)
    assert result.get("action") == "block"
    event_names = [e for e, _ in captured]
    assert "pre_tool_call.blocked" in event_names

                                                                                
                                                                                
    blocked_payload = next(p for e, p in captured if e == "pre_tool_call.blocked")
    assert blocked_payload.get("reason") == "inv-zen-004"
    assert blocked_payload.get("hook_event_name") == "pre_tool_call.blocked"
