-- schemaVersion: 20
-- HADES design release track — audit events raw table.
-- All MCP and handler audit emit calls write here.
-- HADES design wraps this table with a hash-chain + OTel export pipeline
-- WITHOUT schema migration (HADES design note: add computed columns via ALTER TABLE
-- ADD COLUMN or a new supplementary table — never drop/rename existing columns).
-- emitted_at is unix epoch (integer); payload_json is the JSON blob from the caller.
--
-- CHECK constraints (post-review N-7):
--   emitted_at > 0 — defends against accidental zero/negative timestamps
--   from buggy callers; the daemon handler sets time.Now().Unix() so
--   real inserts are always compliant.

CREATE TABLE IF NOT EXISTS audit_events_raw (
    id           TEXT    NOT NULL PRIMARY KEY,  -- UUIDv4 generated by handler
    project_id   TEXT    NOT NULL DEFAULT '',
    type         TEXT    NOT NULL,              -- e.g. "sshexec.started", "audit_review.completed"
    payload_json TEXT    NOT NULL DEFAULT '{}',
    emitted_at   INTEGER NOT NULL CHECK (emitted_at > 0) -- unix epoch; set by daemon handler
);

CREATE INDEX IF NOT EXISTS idx_audit_events_raw_project ON audit_events_raw(project_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_raw_type    ON audit_events_raw(type);
CREATE INDEX IF NOT EXISTS idx_audit_events_raw_ts      ON audit_events_raw(emitted_at);
