package main

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestKnownEventTypes(t *testing.T) {

	want := []string{

		"on_session_start",
		"on_session_end",
		"pre_tool_call",
		"post_tool_call",
		"pre_llm_call",

		"pre_tool_call.blocked",
		"file.edited",
	}
	for _, ev := range want {
		if !isKnownEvent(ev) {
			t.Errorf("event %q not recognized by poster dispatch", ev)
		}
	}
}

func TestParseHookPayload(t *testing.T) {
	raw := `{
		"session_id": "sess-123",
		"cwd": "/path/to/projects/zen-swarm",
		"hook_event_name": "pre_tool_call",
		"tool_name": "Bash",
		"args_summary": {"command": "git status"},
		"task_id": "task-xyz"
	}`
	got, err := parseHookPayload(strings.NewReader(raw))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if got.SessionID != "sess-123" {
		t.Errorf("session_id = %q, want sess-123", got.SessionID)
	}
	if got.HookEventName != "pre_tool_call" {
		t.Errorf("hook_event_name = %q, want pre_tool_call", got.HookEventName)
	}
	if got.ToolName != "Bash" {
		t.Errorf("tool_name = %q, want Bash", got.ToolName)
	}
	if got.TaskID != "task-xyz" {
		t.Errorf("task_id = %q, want task-xyz", got.TaskID)
	}
}

func TestParseHookPayloadBadJSON(t *testing.T) {
	raw := `{not valid json`
	if _, err := parseHookPayload(bytes.NewReader([]byte(raw))); err == nil {
		t.Error("expected error on malformed JSON, got nil")
	}
}

type fakeDaemon struct {
	t        *testing.T
	socket   string
	server   *http.Server
	listener net.Listener
	captured chan []byte
}

func newFakeDaemon(t *testing.T) *fakeDaemon {
	t.Helper()
	dir := t.TempDir()
	sock := filepath.Join(dir, "fake.sock")
	listener, err := net.Listen("unix", sock)
	if err != nil {
		t.Fatalf("uds listen: %v", err)
	}
	fd := &fakeDaemon{t: t, socket: sock, listener: listener, captured: make(chan []byte, 16)}
	mux := http.NewServeMux()
	mux.HandleFunc("/v1/events", func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		select {
		case fd.captured <- body:
		default:
		}
		w.WriteHeader(http.StatusAccepted)
		w.Write([]byte(`{"accepted":1}`))
	})
	fd.server = &http.Server{Handler: mux}
	go fd.server.Serve(listener)
	return fd
}

func (fd *fakeDaemon) close() {
	_ = fd.server.Shutdown(context.Background())
	fd.listener.Close()
}

func TestPostEventToFakeDaemon(t *testing.T) {
	fd := newFakeDaemon(t)
	defer fd.close()
	payload := hookPayload{
		SessionID:     "sess-test",
		CWD:           "/path/to/projects/foo",
		HookEventName: "on_session_start",
		Source:        "startup",
	}
	if err := postEvent(fd.socket, "on_session_start", payload); err != nil {
		t.Fatalf("postEvent: %v", err)
	}
	select {
	case body := <-fd.captured:
		var got []map[string]any
		if err := json.Unmarshal(body, &got); err != nil {
			t.Fatalf("unmarshal captured: %v", err)
		}
		if len(got) != 1 {
			t.Fatalf("captured array len = %d, want 1", len(got))
		}
		if got[0]["type"] != "on_session_start" {
			t.Errorf("type = %v, want on_session_start", got[0]["type"])
		}
		if got[0]["session_id"] != "sess-test" {
			t.Errorf("session_id = %v, want sess-test", got[0]["session_id"])
		}
	case <-time.After(30 * time.Second):
		t.Fatal("daemon did not receive event within 30s")
	}
}

func TestCommitMsgGateAcceptsClean(t *testing.T) {
	payload := hookPayload{
		HookEventName: "pre_tool_call",
		ToolName:      "Bash",
		ArgsSummary:   map[string]any{"command": `git commit -m "feat(foo): add bar"`},
	}
	exit, _ := evaluatePreToolCall(payload)
	if exit != 0 {
		t.Errorf("clean message: exit = %d, want 0", exit)
	}
}

func TestCommitMsgGateRejectsClaudeAttribution(t *testing.T) {
	cases := []string{
		`git commit -m "feat: x\n\nCo-Authored-By: prohibited assistant"`,
		`git commit -m "fix: y\n\nGenerated with prohibited assistant"`,
		`git commit -m "chore: anthropic-sourced"`,
		`git commit -m "feat: z\n\nGenerated by prohibited assistant"`,
	}
	for _, cmd := range cases {
		payload := hookPayload{
			HookEventName: "pre_tool_call",
			ToolName:      "Bash",
			ArgsSummary:   map[string]any{"command": cmd},
		}
		exit, msg := evaluatePreToolCall(payload)
		if exit != 2 {
			t.Errorf("forbidden cmd %q: exit = %d, want 2", cmd, exit)
		}
		if msg == "" {
			t.Errorf("forbidden cmd %q: empty error msg", cmd)
		}
	}
}

func TestCommitMsgGateOnlyChecksGitCommit(t *testing.T) {
	payload := hookPayload{
		HookEventName: "pre_tool_call",
		ToolName:      "Bash",
		ArgsSummary:   map[string]any{"command": "echo 'co-authored-by: Claude'"},
	}
	exit, _ := evaluatePreToolCall(payload)
	if exit != 0 {
		t.Errorf("non-git-commit cmd: exit = %d, want 0", exit)
	}
}

func TestCommitMsgGateSkipsNonBash(t *testing.T) {
	payload := hookPayload{
		HookEventName: "pre_tool_call",
		ToolName:      "Read",
		ArgsSummary:   map[string]any{"file_path": "/foo"},
	}
	exit, _ := evaluatePreToolCall(payload)
	if exit != 0 {
		t.Errorf("non-Bash tool: exit = %d, want 0", exit)
	}
}

func TestProjectFromCWD(t *testing.T) {

	cases := []struct{ in, want string }{
		{"/path/to/projects/zen-swarm", "zen-swarm"},
		{"", ""},
		{"single", "single"},
	}
	for _, c := range cases {
		got := projectFromCWD(c.in)
		if got != c.want {
			t.Errorf("projectFromCWD(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestPayloadFor(t *testing.T) {
	in := hookPayload{
		ToolName:    "Bash",
		ArgsSummary: map[string]any{"command": "git status"},
		Source:      "startup",
	}
	out := payloadFor(in)

	var parsed map[string]any
	if err := json.Unmarshal([]byte(out), &parsed); err != nil {
		t.Fatalf("payloadFor produced invalid JSON: %v", err)
	}
	if parsed["tool_name"] != "Bash" {
		t.Errorf("tool_name = %v", parsed["tool_name"])
	}
}

func TestDaemonSocketEnvPrecedence(t *testing.T) {
	t.Run("ZEN_SWARM_UDS takes precedence", func(t *testing.T) {
		t.Setenv("ZEN_SWARM_UDS", "/tmp/uds-primary.sock")
		t.Setenv("ZEN_DAEMON_SOCKET", "/tmp/fallback.sock")
		got := daemonSocket()
		if got != "/tmp/uds-primary.sock" {
			t.Errorf("daemonSocket() = %q, want /tmp/uds-primary.sock", got)
		}
	})
	t.Run("ZEN_DAEMON_SOCKET fallback", func(t *testing.T) {
		t.Setenv("ZEN_SWARM_UDS", "")
		t.Setenv("ZEN_DAEMON_SOCKET", "/tmp/fallback.sock")
		got := daemonSocket()
		if got != "/tmp/fallback.sock" {
			t.Errorf("daemonSocket() = %q, want /tmp/fallback.sock", got)
		}
	})
	t.Run("default when no env vars", func(t *testing.T) {
		t.Setenv("ZEN_SWARM_UDS", "")
		t.Setenv("ZEN_DAEMON_SOCKET", "")
		got := daemonSocket()
		if got != defaultDaemonSocket {
			t.Errorf("daemonSocket() = %q, want %q", got, defaultDaemonSocket)
		}
	})
}

func TestPayloadForAllEmpty(t *testing.T) {
	in := hookPayload{}
	out := payloadFor(in)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(out), &parsed); err != nil {
		t.Fatalf("payloadFor(empty) produced invalid JSON: %v", err)
	}

	if len(parsed) != 0 {
		t.Errorf("payloadFor(empty) = %v, want empty map", parsed)
	}
}

func TestPayloadForAllSet(t *testing.T) {
	in := hookPayload{
		ToolName:      "Bash",
		ArgsSummary:   map[string]any{"command": "ls"},
		ResultKind:    "text",
		ResultSize:    42,
		Source:        "startup",
		HookEventName: "pre_tool_call",
		MessagesCount: 10,
		Reason:        "inv-zen-004",
		Completed:     true,
		Interrupted:   true,
	}
	out := payloadFor(in)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(out), &parsed); err != nil {
		t.Fatalf("payloadFor(all-set) produced invalid JSON: %v", err)
	}
	checks := map[string]any{
		"tool_name":       "Bash",
		"result_kind":     "text",
		"source":          "startup",
		"hook_event_name": "pre_tool_call",
		"reason":          "inv-zen-004",
		"completed":       true,
		"interrupted":     true,
	}
	for k, wantV := range checks {
		if parsed[k] != wantV {
			t.Errorf("payloadFor[%q] = %v, want %v", k, parsed[k], wantV)
		}
	}

	if parsed["result_size"] != float64(42) {
		t.Errorf("payloadFor[result_size] = %v, want 42", parsed["result_size"])
	}
	if parsed["messages_count"] != float64(10) {
		t.Errorf("payloadFor[messages_count] = %v, want 10", parsed["messages_count"])
	}
}

func TestPayloadForResultSizeZero(t *testing.T) {

	in := hookPayload{ResultSize: 0, ToolName: "Read"}
	out := payloadFor(in)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(out), &parsed); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}
	if _, ok := parsed["result_size"]; ok {
		t.Error("result_size should be absent when zero")
	}
}

func TestPayloadForMessagesCountZero(t *testing.T) {

	in := hookPayload{MessagesCount: 0, Source: "startup"}
	out := payloadFor(in)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(out), &parsed); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}
	if _, ok := parsed["messages_count"]; ok {
		t.Error("messages_count should be absent when zero")
	}
}

func TestPayloadForCompletedFalse(t *testing.T) {

	in := hookPayload{Completed: false, Interrupted: false, Source: "resume"}
	out := payloadFor(in)
	var parsed map[string]any
	if err := json.Unmarshal([]byte(out), &parsed); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}
	if _, ok := parsed["completed"]; ok {
		t.Error("completed should be absent when false")
	}
	if _, ok := parsed["interrupted"]; ok {
		t.Error("interrupted should be absent when false")
	}
}

func TestPostEventDaemonUnreachable(t *testing.T) {

	err := postEvent("/tmp/zen-event-poster-nonexistent-test.sock", "on_session_start", hookPayload{
		SessionID: "sess-fail",
		CWD:       "/tmp",
	})
	if err == nil {
		t.Error("expected error when daemon socket is unreachable, got nil")
	}
}

func TestPostEventDaemon5xx(t *testing.T) {

	dir := t.TempDir()
	sock := filepath.Join(dir, "err.sock")
	listener, err := net.Listen("unix", sock)
	if err != nil {
		t.Fatalf("uds listen: %v", err)
	}
	mux := http.NewServeMux()
	mux.HandleFunc("/v1/events", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(`{"error":"internal"}`))
	})
	srv := &http.Server{Handler: mux}
	go srv.Serve(listener)
	defer func() {
		_ = srv.Shutdown(context.Background())
		listener.Close()
	}()

	err = postEvent(sock, "on_session_start", hookPayload{
		SessionID: "sess-5xx",
		CWD:       "/tmp",
	})
	if err == nil {
		t.Error("expected error on 5xx response, got nil")
	}
	if !strings.Contains(err.Error(), "500") {
		t.Errorf("error should mention status code 500: %v", err)
	}
}

func TestExtractCommitMessageNoFlag(t *testing.T) {

	got := extractCommitMessage("git commit --amend")
	if got != "" {
		t.Errorf("extractCommitMessage(no -m) = %q, want empty", got)
	}
}

func TestExtractCommitMessageSingleQuotes(t *testing.T) {
	got := extractCommitMessage(`git commit -m 'feat: single quoted'`)
	if got != "feat: single quoted" {
		t.Errorf("extractCommitMessage(single quotes) = %q", got)
	}
}

func TestExtractCommitMessageDoubleQuotes(t *testing.T) {
	got := extractCommitMessage(`git commit -m "feat: double quoted"`)
	if got != "feat: double quoted" {
		t.Errorf("extractCommitMessage(double quotes) = %q", got)
	}
}

func TestExtractCommitMessageMultiLine(t *testing.T) {

	got := extractCommitMessage(`git commit -m "feat: title\n\nBody text here"`)
	if got == "" {
		t.Error("extractCommitMessage(multi-line) returned empty")
	}
}

func TestIsKnownEventRejectsUnknown(t *testing.T) {
	unknowns := []string{"unknown_event", "on_tool_use", "", "post_llm_call"}
	for _, ev := range unknowns {
		if isKnownEvent(ev) {
			t.Errorf("isKnownEvent(%q) = true, want false", ev)
		}
	}
}

func TestCommitMsgGateNoArgsSummary(t *testing.T) {

	payload := hookPayload{
		HookEventName: "pre_tool_call",
		ToolName:      "Bash",
		ArgsSummary:   nil,
	}
	exit, _ := evaluatePreToolCall(payload)
	if exit != 0 {
		t.Errorf("nil ArgsSummary: exit = %d, want 0", exit)
	}
}

func TestCommitMsgGateGitCommitNoMFlag(t *testing.T) {

	payload := hookPayload{
		HookEventName: "pre_tool_call",
		ToolName:      "Bash",
		ArgsSummary:   map[string]any{"command": "git commit --amend --no-edit"},
	}
	exit, _ := evaluatePreToolCall(payload)
	if exit != 0 {
		t.Errorf("git commit no -m: exit = %d, want 0", exit)
	}
}

func TestProjectFromCWDNoSlash(t *testing.T) {

	got := projectFromCWD("myproject")
	if got != "myproject" {
		t.Errorf("projectFromCWD(no-slash) = %q, want myproject", got)
	}
}

func TestProjectFromCWDRootSlash(t *testing.T) {

	got := projectFromCWD("/")
	if got != "" {
		t.Errorf("projectFromCWD(/) = %q, want empty", got)
	}
}

func TestPostEventHeaders(t *testing.T) {
	dir := t.TempDir()
	sock := filepath.Join(dir, "hdr.sock")
	listener, err := net.Listen("unix", sock)
	if err != nil {
		t.Fatalf("uds listen: %v", err)
	}
	type capturedHeaders struct {
		project string
		session string
	}
	ch := make(chan capturedHeaders, 1)
	mux := http.NewServeMux()
	mux.HandleFunc("/v1/events", func(w http.ResponseWriter, r *http.Request) {
		ch <- capturedHeaders{
			project: r.Header.Get("X-Zen-Project"),
			session: r.Header.Get("X-Zen-Session"),
		}
		w.WriteHeader(http.StatusAccepted)
		w.Write([]byte(`{"accepted":1}`))
	})
	srv := &http.Server{Handler: mux}
	go srv.Serve(listener)
	defer func() {
		_ = srv.Shutdown(context.Background())
		listener.Close()
	}()

	payload := hookPayload{
		SessionID: "sess-hdr-test",
		CWD:       "/home/user/myproject",
	}
	if err := postEvent(sock, "on_session_start", payload); err != nil {
		t.Fatalf("postEvent: %v", err)
	}
	select {
	case hdrs := <-ch:
		if hdrs.project != "myproject" {
			t.Errorf("X-Zen-Project = %q, want myproject", hdrs.project)
		}
		if hdrs.session != "sess-hdr-test" {
			t.Errorf("X-Zen-Session = %q, want sess-hdr-test", hdrs.session)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("daemon did not receive headers within 30s")
	}
}

func TestPostEventJSONArrayShape(t *testing.T) {
	dir := t.TempDir()
	sock := filepath.Join(dir, "shape.sock")
	listener, err := net.Listen("unix", sock)
	if err != nil {
		t.Fatalf("uds listen: %v", err)
	}
	bodies := make(chan []byte, 1)
	mux := http.NewServeMux()
	mux.HandleFunc("/v1/events", func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		bodies <- body
		w.WriteHeader(http.StatusAccepted)
	})
	srv := &http.Server{Handler: mux}
	go srv.Serve(listener)
	defer func() {
		_ = srv.Shutdown(context.Background())
		listener.Close()
	}()

	payload := hookPayload{
		SessionID: "sess-shape",
		CWD:       "/projects/zen-swarm",
		TaskID:    "task-abc",
	}
	if err := postEvent(sock, "post_tool_call", payload); err != nil {
		t.Fatalf("postEvent: %v", err)
	}
	select {
	case body := <-bodies:
		var rows []eventRow
		if err := json.Unmarshal(body, &rows); err != nil {
			t.Fatalf("unmarshal as []eventRow: %v", err)
		}
		if len(rows) != 1 {
			t.Fatalf("rows count = %d, want 1", len(rows))
		}
		row := rows[0]
		if row.Type != "post_tool_call" {
			t.Errorf("row.Type = %q, want post_tool_call", row.Type)
		}
		if row.SessionID != "sess-shape" {
			t.Errorf("row.SessionID = %q, want sess-shape", row.SessionID)
		}
		if row.Project != "zen-swarm" {
			t.Errorf("row.Project = %q, want zen-swarm", row.Project)
		}
		if row.TaskID != "task-abc" {
			t.Errorf("row.TaskID = %q, want task-abc", row.TaskID)
		}
		if row.TS == 0 {
			t.Error("row.TS should be non-zero")
		}
	case <-time.After(30 * time.Second):
		t.Fatal("daemon did not receive request within 30s")
	}
}

func TestDaemonSocketEnvIsolation(t *testing.T) {

	original := os.Getenv("ZEN_SWARM_UDS")
	t.Setenv("ZEN_SWARM_UDS", "/tmp/isolation-test.sock")
	got := daemonSocket()
	if got != "/tmp/isolation-test.sock" {
		t.Errorf("got %q", got)
	}

	_ = original
}

func TestRunNoArgs(t *testing.T) {
	code := run([]string{}, strings.NewReader("{}"), "/tmp/nonexistent.sock")
	if code != 1 {
		t.Errorf("run(no args) = %d, want 1", code)
	}
}

func TestRunUnknownEvent(t *testing.T) {
	code := run([]string{"unknown_event"}, strings.NewReader("{}"), "/tmp/nonexistent.sock")
	if code != 1 {
		t.Errorf("run(unknown event) = %d, want 1", code)
	}
}

func TestRunBadJSON(t *testing.T) {
	code := run([]string{"on_session_start"}, strings.NewReader("{bad json}"), "/tmp/nonexistent.sock")
	if code != 1 {
		t.Errorf("run(bad JSON) = %d, want 1", code)
	}
}

func TestRunDaemonUnreachable(t *testing.T) {
	payload := `{"session_id":"sess-run","cwd":"/tmp"}`
	code := run([]string{"on_session_start"}, strings.NewReader(payload), "/tmp/zen-run-nonexistent.sock")
	// Daemon unreachable → exit 1 (warning, not block)
	if code != 1 {
		t.Errorf("run(daemon unreachable) = %d, want 1", code)
	}
}

func TestRunSuccessWithFakeDaemon(t *testing.T) {
	fd := newFakeDaemon(t)
	defer fd.close()
	payload := `{"session_id":"sess-run-ok","cwd":"/projects/foo"}`
	code := run([]string{"on_session_start"}, strings.NewReader(payload), fd.socket)
	if code != 0 {
		t.Errorf("run(success) = %d, want 0", code)
	}
}

func TestRunPreToolCallGateBlock(t *testing.T) {
	fd := newFakeDaemon(t)
	defer fd.close()
	payload := `{
		"session_id":"sess-gate",
		"cwd":"/tmp",
		"tool_name":"Bash",
		"args_summary":{"command":"git commit -m \"chore: anthropic test\""}
	}`
	code := run([]string{"pre_tool_call"}, strings.NewReader(payload), fd.socket)
	if code != 2 {
		t.Errorf("run(pre_tool_call gate block) = %d, want 2", code)
	}
}

func TestRunPreToolCallGatePass(t *testing.T) {
	fd := newFakeDaemon(t)
	defer fd.close()
	payload := `{
		"session_id":"sess-gate-ok",
		"cwd":"/tmp",
		"tool_name":"Bash",
		"args_summary":{"command":"git commit -m \"feat: clean message\""}
	}`
	code := run([]string{"pre_tool_call"}, strings.NewReader(payload), fd.socket)
	if code != 0 {
		t.Errorf("run(pre_tool_call gate pass) = %d, want 0", code)
	}
}

func shortFakeDaemon(t *testing.T, suffix string) *fakeDaemon {
	t.Helper()
	sock := filepath.Join(os.TempDir(), "zep-"+suffix+".sock")

	_ = os.Remove(sock)
	listener, err := net.Listen("unix", sock)
	if err != nil {
		t.Fatalf("uds listen: %v", err)
	}
	fd := &fakeDaemon{t: t, socket: sock, listener: listener, captured: make(chan []byte, 16)}
	mux := http.NewServeMux()
	mux.HandleFunc("/v1/events", func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		select {
		case fd.captured <- body:
		default:
		}
		w.WriteHeader(http.StatusAccepted)
		w.Write([]byte(`{"accepted":1}`))
	})
	fd.server = &http.Server{Handler: mux}
	go fd.server.Serve(listener)
	t.Cleanup(func() {
		_ = fd.server.Shutdown(context.Background())
		fd.listener.Close()
		_ = os.Remove(sock)
	})
	return fd
}

func TestRunPreToolCallBlockAlsoEmitsBlockedEvent(t *testing.T) {

	fd := shortFakeDaemon(t, "blocked")
	payload := `{
		"session_id":"sess-blocked",
		"cwd":"/projects/zen-swarm",
		"tool_name":"Bash",
		"args_summary":{"command":"git commit -m \"fix: claude attribution\""}
	}`
	code := run([]string{"pre_tool_call"}, strings.NewReader(payload), fd.socket)
	if code != 2 {
		t.Errorf("run = %d, want 2", code)
	}

	select {
	case body := <-fd.captured:
		var got []map[string]any
		if err := json.Unmarshal(body, &got); err != nil {
			t.Fatalf("unmarshal: %v", err)
		}
		if len(got) < 1 {
			t.Fatal("no events captured")
		}
		if got[0]["type"] != "pre_tool_call.blocked" {
			t.Errorf("type = %v, want pre_tool_call.blocked", got[0]["type"])
		}
	case <-time.After(30 * time.Second):
		t.Fatal("daemon did not receive blocked event within 30s")
	}
}
