// SPDX-License-Identifier: MIT
package commenthygiene

import "regexp"

type ClassifierDecision int

const (
	DecisionKeep ClassifierDecision = iota

	DecisionDelete

	DecisionRewrite
)

func (d ClassifierDecision) String() string {
	switch d {
	case DecisionKeep:
		return "KEEP"
	case DecisionDelete:
		return "DELETE"
	case DecisionRewrite:
		return "REWRITE"
	default:
		return "UNKNOWN"
	}
}

var rotPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?m)^\s*//\s*Plan [0-9]+`),
	regexp.MustCompile(`(?m)^\s*//\s*v0\.[0-9]+\.[0-9]+`),
	regexp.MustCompile(`(?m)^\s*//\s*TODO\s+[^(]`),
	regexp.MustCompile(`(?im)^\s*//\s*(added by claude|generated by)`),
	regexp.MustCompile(`(?m)^\s*//\s*(per spec|per plan|see) docs/superpowers`),
}

var loadBearingPatterns = []*regexp.Regexp{
	regexp.MustCompile(`inv-zen-[0-9A-Za-z]+`),
	regexp.MustCompile(`MUST\s+`),
	regexp.MustCompile(`workaround:`),
	regexp.MustCompile(`race\s+`),
}

func Classify(commentLine string) ClassifierDecision {
	for _, p := range loadBearingPatterns {
		if p.MatchString(commentLine) {
			return DecisionKeep
		}
	}
	for _, p := range rotPatterns {
		if p.MatchString(commentLine) {
			return DecisionDelete
		}
	}

	return DecisionKeep
}
