//go:build !race
// +build !race

package compliance

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cbip-solutions/hades-system/internal/adr"
)

func TestADR0090Frontmatter(t *testing.T) {
	repoRoot := findRepoRoot(t)
	adrPath := filepath.Join(repoRoot, "docs", "decisions", "0090-versionrag-architecture.md")

	body, err := os.ReadFile(adrPath)
	if err != nil {
		t.Fatalf("read ADR-0090: %v", err)
	}

	v, err := adr.NewValidator(filepath.Join(repoRoot, "docs", "decisions", "_schema.json"))
	if err != nil {
		t.Fatalf("load validator: %v", err)
	}

	parsed, err := v.ParseAndValidate(adrPath, body)
	if err != nil {
		t.Fatalf("ADR-0090 schema violation: %v", err)
	}

	if parsed.Frontmatter.ID != "ADR-0090" {
		t.Errorf("id = %q; want ADR-0090", parsed.Frontmatter.ID)
	}
	if parsed.Frontmatter.Plan != "plan-14" {
		t.Errorf("plan = %q; want plan-14", parsed.Frontmatter.Plan)
	}

	bodyStr := string(body)

	mandatory := []string{
		"## Context",
		"## Decision",
		"## Consequences",
		"## Doctrine alignment",
		"## SOTA references",
		"## Plan impact",
		"## Related ADRs",
	}
	for _, hdr := range mandatory {
		if !strings.Contains(bodyStr, hdr) {
			t.Errorf("missing section %q", hdr)
		}
	}

	sotaSources := []string{
		"VersionRAG",
		"2510.08109",
		"Context7",
		"pkg.go.dev",
		"docs.rs",
		"Particula",
		"Keep-a-Changelog",
		"DeepDiff",
	}
	for _, src := range sotaSources {
		if !strings.Contains(bodyStr, src) {
			t.Errorf("SOTA missing %q", src)
		}
	}

	cascade := []string{
		"--version",
		"go.mod",
		"pyproject.toml",
		"package.json",
		"Cargo.toml",
		"in-query regex",
		"Haiku classifier",
		"latest_stable_version",
	}
	for _, c := range cascade {
		if !strings.Contains(bodyStr, c) {
			t.Errorf("5-layer cascade detail missing %q", c)
		}
	}

	schemaCols := []string{
		"version_introduced",
		"version_deprecated",
		"stable_in_json",
		"ecosystem_changes",
	}
	for _, col := range schemaCols {
		if !strings.Contains(bodyStr, col) {
			t.Errorf("schema column %q not referenced", col)
		}
	}

	expectedRelates := []string{"ADR-0006", "ADR-0067", "ADR-0087", "ADR-0091"}
	for _, rel := range expectedRelates {
		found := false
		for _, r := range parsed.Frontmatter.RelatesTo {
			if r == rel {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("relates-to missing %q", rel)
		}
	}

	for _, banned := range []string{
		"Co-Authored-By: prohibited assistant",
		"Generated with prohibited assistant",
		"Generated by prohibited assistant",
	} {
		if strings.Contains(bodyStr, banned) {
			t.Errorf("ADR-0090 includes BANNED attribution %q (inv-zen-004)", banned)
		}
	}
}
