// SPDX-License-Identifier: MIT

// tests/compliance/inv_zen_287_spdx_headers_test.go
//
// Compliance test for inv-zen-287: every production .go/.py/.sh file MUST
// declare `SPDX-License-Identifier: MIT` within its first 10 lines.
//
// Per Plan 15 decisión 15 (2026-05-24): identifier is MIT (whole project
// including internal/caronte/; no special-case treatment).
//
// Production-file boundary (single source of truth — must stay in sync
// with `scripts/insert_spdx_headers.sh` + `lints/no-missing-spdx-header.yaml`):
//
//	Excluded paths (no SPDX required):
//	  - vendor/, .git/, node_modules/, .venv/, venv/, .tox/, .mypy_cache/,
//	    .pytest_cache/, __pycache__/, bin/, dist/, build/
//	  - private-tier1-module/ (Phase B extraction target)
//	  - **/testdata/** (test fixtures — lint exclude rule)
//	  - **/*_test.go (test files — lint exclude rule)
//	  - files marked "Code generated by ... DO NOT EDIT" (first 4 KiB)
//
// Remediation: `scripts/insert_spdx_headers.sh` (idempotent bulk inserter).
package compliance

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func findRepoRootInvZen287(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("findRepoRootInvZen287: could not locate go.mod from %v", dir)
	return ""
}

// TestInvZen287_SPDXHeadersPresent walks the repo and asserts every .go/.py/.sh
// production file declares SPDX-License-Identifier: MIT within the first 10
// lines. Production-file boundary mirrors scripts/insert_spdx_headers.sh.
func TestInvZen287_SPDXHeadersPresent(t *testing.T) {
	root := findRepoRootInvZen287(t)
	excludedRoots := []string{
		filepath.Join(root, "vendor"),
		filepath.Join(root, ".git"),
		filepath.Join(root, "node_modules"),
		filepath.Join(root, ".venv"),
		filepath.Join(root, "venv"),
		filepath.Join(root, ".tox"),
		filepath.Join(root, ".mypy_cache"),
		filepath.Join(root, ".pytest_cache"),
		filepath.Join(root, "__pycache__"),
		filepath.Join(root, "bin"),
		filepath.Join(root, "dist"),
		filepath.Join(root, "build"),
		filepath.Join(root, "internal", "anthropic-bypass"),
	}

	var missing []string

	walkErr := filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil || info == nil {
			return nil
		}

		if info.IsDir() {
			for _, ex := range excludedRoots {
				if p == ex {
					return filepath.SkipDir
				}
			}

			switch info.Name() {
			case "testdata", ".venv", "venv", ".tox", ".mypy_cache", ".pytest_cache", "__pycache__":
				return filepath.SkipDir
			}
			return nil
		}

		ext := filepath.Ext(p)
		if ext != ".go" && ext != ".py" && ext != ".sh" {
			return nil
		}

		if strings.HasSuffix(p, "_test.go") {
			return nil
		}

		data, readErr := os.ReadFile(p)
		if readErr != nil {
			t.Logf("inv-zen-287: read %s: %v (skipped)", p, readErr)
			return nil
		}

		head := string(data)
		if len(head) > 4096 {
			head = head[:4096]
		}
		if strings.Contains(head, "Code generated by") || strings.Contains(head, "DO NOT EDIT") {

			if strings.Contains(head, "Code generated by") {
				return nil
			}
		}

		// inv-zen-287: SPDX-License-Identifier: MIT within first 10 lines.
		lines := strings.SplitN(string(data), "\n", 11)
		found := false
		for i, line := range lines {
			if i >= 10 {
				break
			}
			if strings.Contains(line, "SPDX-License-Identifier:") && strings.Contains(line, "MIT") {
				found = true
				break
			}
		}
		if !found {
			rel, _ := filepath.Rel(root, p)
			missing = append(missing, rel)
		}
		return nil
	})

	if walkErr != nil {
		t.Fatalf("inv-zen-287: walk failed: %v", walkErr)
	}

	if len(missing) > 0 {
		t.Errorf("inv-zen-287: %d production files missing SPDX-MIT header", len(missing))
		for i, m := range missing {
			if i >= 20 {
				t.Logf("  ... and %d more", len(missing)-20)
				break
			}
			t.Logf("  %s", m)
		}
		t.Logf("Remediation: scripts/insert_spdx_headers.sh")
	}
}
