package compliance

import (
	"bufio"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

func repoRoot338(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("repoRoot: getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("repoRoot: go.mod not found walking up from %s", dir)
		}
		dir = parent
	}
}

func skipCommentHygieneDir(base string) bool {
	switch base {
	case ".git", "vendor", "testdata", "node_modules", ".venv", "venv", ".tox",
		".mypy_cache", ".pytest_cache", "__pycache__":
		return true
	default:
		return false
	}
}

func walkGoSource(t *testing.T, check func(path string, lineno int, line string)) {
	t.Helper()
	root := repoRoot338(t)
	for _, subdir := range []string{"internal", "cmd"} {
		err := filepath.Walk(filepath.Join(root, subdir), func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				base := filepath.Base(path)
				if skipCommentHygieneDir(base) {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") {
				return nil
			}
			f, err := os.Open(path)
			if err != nil {
				return err
			}
			defer f.Close()
			scanner := bufio.NewScanner(f)
			scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
			lineno := 0
			for scanner.Scan() {
				lineno++
				check(path, lineno, scanner.Text())
			}
			return scanner.Err()
		})
		if err != nil {
			t.Fatalf("walkGoSource: walk %s: %v", subdir, err)
		}
	}
}

func walkPythonSource(t *testing.T, check func(path string, lineno int, line string)) {
	t.Helper()
	root := repoRoot338(t)
	err := filepath.Walk(filepath.Join(root, "plugin"), func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			base := filepath.Base(path)
			if skipCommentHygieneDir(base) {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".py") {
			return nil
		}
		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		scanner := bufio.NewScanner(f)
		scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
		lineno := 0
		for scanner.Scan() {
			lineno++
			check(path, lineno, scanner.Text())
		}
		return scanner.Err()
	})
	if err != nil {
		t.Fatalf("walkPythonSource: walk plugin: %v", err)
	}
}

func reportViolations(t *testing.T, invariant string, vios []string) {
	t.Helper()
	if len(vios) == 0 {
		return
	}
	t.Errorf("%s: %d violation(s) detected:", invariant, len(vios))
	for i, v := range vios {
		if i >= 20 {
			t.Logf("      ... and %d more", len(vios)-i)
			break
		}
		t.Logf("      %s", v)
	}
}

func formatViolation(path string, lineno int, line string) string {
	return filepath.Base(path) + ":" + strconv.Itoa(lineno) + ": " + strings.TrimSpace(line)
}

var (
	goPlanN   = regexp.MustCompile(`^\s*//\s*Plan [0-9]+`)
	goVersion = regexp.MustCompile(`^\s*//\s*v0\.[0-9]+\.[0-9]+`)

	goMarker = regexp.MustCompile(`^\s*//\s*(TODO|FIXME|XXX|HACK|NOTE)([^(\[]|\s)`)
	goAILeak = regexp.MustCompile(`(?i)^\s*//\s*(added by claude|generated by ai|created by claude|authored by ai)`)
)

var (
	pyPlanN   = regexp.MustCompile(`^\s*#\s*Plan [0-9]+`)
	pyVersion = regexp.MustCompile(`^\s*#\s*v0\.[0-9]+\.[0-9]+`)
	pyMarker  = regexp.MustCompile(`^\s*#\s*(TODO|FIXME|XXX|HACK|NOTE)([^(\[]|\s)`)
	pyAILeak  = regexp.MustCompile(`(?i)^\s*#\s*(added by claude|generated by ai|created by claude|authored by ai)`)
)

func TestInvZen338_NoPlanNRotInGo(t *testing.T) {
	var violations []string
	walkGoSource(t, func(path string, lineno int, line string) {
		if goPlanN.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-338", violations)
	if len(violations) > 0 {
		t.Logf("auto-fix: bash scripts/comment_prepass.sh --apply")
	}
}

func TestInvZen338_NoPlanNRotInPython(t *testing.T) {
	var violations []string
	walkPythonSource(t, func(path string, lineno int, line string) {
		if pyPlanN.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-338", violations)
	if len(violations) > 0 {
		t.Logf("auto-fix: bash scripts/comment_prepass.sh --apply")
	}
}

func TestInvZen339_NoVersionRotInGo(t *testing.T) {
	var violations []string
	walkGoSource(t, func(path string, lineno int, line string) {
		if goVersion.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-339", violations)
	if len(violations) > 0 {
		t.Logf("hint: legit version-pins belong in constants, not comments")
	}
}

func TestInvZen339_NoVersionRotInPython(t *testing.T) {
	var violations []string
	walkPythonSource(t, func(path string, lineno int, line string) {
		if pyVersion.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-339", violations)
	if len(violations) > 0 {
		t.Logf("hint: legit version-pins belong in constants, not comments")
	}
}

func TestInvZen340_NoMarkersWithoutOwnerInGo(t *testing.T) {
	var violations []string
	walkGoSource(t, func(path string, lineno int, line string) {
		if goMarker.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-340", violations)
	if len(violations) > 0 {
		t.Logf("hint: convert orphan markers to TODO(owner): or TODO[YYYY-MM-DD]: per K-6 convention")
	}
}

func TestInvZen340_NoMarkersWithoutOwnerInPython(t *testing.T) {
	var violations []string
	walkPythonSource(t, func(path string, lineno int, line string) {
		if pyMarker.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-340", violations)
	if len(violations) > 0 {
		t.Logf("hint: convert orphan markers to TODO(owner): or TODO[YYYY-MM-DD]: per K-6 convention")
	}
}

func TestInvZen341_NoAIAttributionInGo(t *testing.T) {
	var violations []string
	walkGoSource(t, func(path string, lineno int, line string) {
		if goAILeak.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-341", violations)
	if len(violations) > 0 {
		t.Logf("hint: AI-attribution in code comments violates CLAUDE.md hard rule #1 (no Claude attribution)")
	}
}

func TestInvZen341_NoAIAttributionInPython(t *testing.T) {
	var violations []string
	walkPythonSource(t, func(path string, lineno int, line string) {
		if pyAILeak.MatchString(line) {
			violations = append(violations, formatViolation(path, lineno, line))
		}
	})
	reportViolations(t, "inv-zen-341", violations)
	if len(violations) > 0 {
		t.Logf("hint: AI-attribution in code comments violates CLAUDE.md hard rule #1 (no Claude attribution)")
	}
}

func TestInvZen342_ExportedIdentifiersHaveGodoc(t *testing.T) {
	if _, err := exec.LookPath("golangci-lint"); err != nil {
		t.Skip("inv-zen-342: golangci-lint not installed; gate enforced on CI via Phase G aggregator")
	}
	root := repoRoot338(t)
	cmd := exec.Command(
		"bash",
		"scripts/verify_godoc_clean.sh",
	)
	cmd.Dir = root
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Errorf("inv-zen-342: verify_godoc_clean.sh failed:\n%s", out)
		t.Logf("hint: add godoc-format doc comment to each exported identifier (// Name does ...)")
		return
	}

}

func TestInvZen343_GatesExitZero(t *testing.T) {
	if _, err := exec.LookPath("make"); err != nil {
		t.Skip("inv-zen-343: make not installed; gate enforced on CI via Phase G aggregator")
	}
	root := repoRoot338(t)
	for _, target := range []string{"verify-no-task-context-comments", "verify-godoc-clean"} {
		t.Run(target, func(t *testing.T) {
			cmd := exec.Command("make", "-C", root, target)
			out, err := cmd.CombinedOutput()
			if err != nil {

				if strings.Contains(string(out), "No rule to make target") {
					t.Skipf("inv-zen-343: make target %q missing; gate enforced on CI", target)
					return
				}
				t.Errorf("inv-zen-343: make %s failed:\n%s", target, out)
			}
		})
	}
}
