package compliance

import (
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	return filepath.Dir(filepath.Dir(filepath.Dir(file)))
}

func TestInvZen004NoClaudeAttribution(t *testing.T) {
	root := repoRoot(t)
	cmd := exec.Command("git", "-C", root, "log", "--pretty=%B")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Skipf("git log unavailable: %v", err)
	}
	pattern := strings.ToLower(string(out))
	for _, banned := range []string{
		"co-authored-by: claude",
		"generated with claude",
		"generated by claude",
		"generated with anthropic",
		"co-authored-by: anthropic",
	} {
		if strings.Contains(pattern, banned) {
			t.Errorf("inv-zen-004 violated: commit log contains %q", banned)
		}
	}
}

func TestInvZen024VersionedAPI(t *testing.T) {
	root := repoRoot(t)
	cmd := exec.Command("grep", "-n", "HandleFunc", filepath.Join(root, "internal/daemon/server.go"))
	out, err := cmd.CombinedOutput()
	if err != nil {

		t.Skipf("grep failed: %v", err)
	}
	for _, line := range strings.Split(string(out), "\n") {
		if line == "" {
			continue
		}

		if !strings.Contains(line, "/v1/") {
			t.Errorf("inv-zen-024 violated: HandleFunc not under /v1/: %s", line)
		}
	}
}

func TestInvZen031BypassNoThirdPartyImports(t *testing.T) {
	root := repoRoot(t)
	bypassDir := filepath.Join(root, "private-tier1-module")

	cmd := exec.Command("grep", "-rEn",
		`^import\s+"|^\s+"`,
		bypassDir,
	)
	out, _ := cmd.CombinedOutput()

	allowed := []string{
		`"github.com/cbip-solutions/hades-system/internal/errors"`,
		`"github.com/cbip-solutions/hades-system/internal/redact"`,

		`"github.com/cbip-solutions/hades-system/internal/manualkeychain"`,

		`"github.com/keybase/go-keychain"`,

		`"golang.org/x/sync/semaphore"`,

		`"github.com/santhosh-tekuri/jsonschema/v5"`,
	}
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		if idx := strings.Index(line, ".go:"); idx >= 0 {
			rest := line[idx+len(".go:"):]
			if k := strings.Index(rest, ":"); k >= 0 {
				line = strings.TrimSpace(rest[k+1:])
			}
		}

		if !isImportLine(line) {
			continue
		}

		i := strings.Index(line, `"`)
		j := strings.LastIndex(line, `"`)
		if i < 0 || j <= i {
			continue
		}
		imp := line[i : j+1]

		if isAllowedImport(imp, allowed) {
			continue
		}
		t.Errorf("inv-zen-031 violated: bypass module imports %s in line %q", imp, line)
	}
}

func isImportLine(line string) bool {
	if strings.HasPrefix(line, "import ") {
		return true
	}

	if !strings.HasSuffix(line, `"`) {
		return false
	}

	first := strings.IndexByte(line, '"')
	if first == 0 {

		return true
	}
	prefix := strings.TrimSpace(line[:first])
	if prefix == "" || prefix == "_" || prefix == "." {
		return true
	}

	for _, r := range prefix {
		if !(r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

func isAllowedImport(imp string, allowed []string) bool {
	for _, a := range allowed {
		if imp == a {
			return true
		}
	}

	trimmed := strings.Trim(imp, `"`)
	first := strings.Index(trimmed, "/")
	if first == -1 {
		return true
	}
	if !strings.Contains(trimmed[:first], ".") {
		return true
	}
	return false
}

func TestInvZen046DefaultPathIsLocal(t *testing.T) {
	t.Setenv("HOME", "/tmp/zen-test-home")
	t.Setenv("XDG_DATA_HOME", "")

	t.Log("inv-zen-046: store.DefaultPath() must return path under $HOME or $XDG_DATA_HOME")
}
