// SPDX-License-Identifier: MIT
// Fixture: regex-scan witness, NOT a compile target.
//
// The file's shape (imports + interface declaration) is what the K-4
// grpcstub test's goGrpcStubRefs regex consumes; it intentionally does
// NOT compile (the `proto "greeter.v1"` import alias points to an
// unresolvable module path; the var initializer at line 59 references
// types from another fixture file under a different package alias).
//
// Do NOT try `go build./tests/integration/plan20/grpcstub/fixtures/...`.
// By design the fixture exists ONLY to exercise the regex + link
// resolution path; the previous header (`Code generated by
// protoc-gen-go-grpc. DO NOT EDIT.`) was a fiction kept so the file
// looked like a real generated stub at a glance — that fiction is now
// explicit so future readers do not waste time chasing a "broken" build.
//
// Carries the load-bearing two anchors goGrpcStubRefs scan
// matches:
//
// 1. A `proto "..."` import alias line — the regex `^\s*(?:proto|api|spec|pb)\s+"([^"]+)"`
// captures the import path; the captured group becomes the
// StubReference.ProtoPackage.
// 2. A `type GreeterServer interface {... }` declaration with exactly
// one exported PascalCase RPC method declaration line — the regex
// `(?s)type\s+(\w+)Server\s+interface\s*\{(.*?)\}` captures Greeter
// + the body; `(?m)^\s*(\w+)\s*\(` captures Hello inside.
//
// The proto package path the regex matches is `greeter.v1` (the
// canonical.proto package the server's greeter.proto declares).
package greeter

import (
	context "context"

	proto "greeter.v1"
)

type GreeterClient interface {
	Hello(ctx context.Context, in *GreeterRequest, opts ...interface{}) (*GreeterReply, error)
}

type GreeterServer interface {
	Hello(context.Context, *GreeterRequest) (*GreeterReply, error)
	mustEmbedUnimplementedGreeterServer()
}

type greeterClientImpl struct{}

func NewGreeterClient(_ interface{}) GreeterClient { return &greeterClientImpl{} }

func (greeterClientImpl) Hello(_ context.Context, in *GreeterRequest, _ ...interface{}) (*GreeterReply, error) {
	return &GreeterReply{Message: "stub reply for " + in.Name}, nil
}

var _ = proto.GreeterRequest{}
var _ = context.Background
