// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// - protoc-gen-go v1.31.0
// - protoc v3.21.12
// source: greeter.proto
//
// protoc-gen-go would emit for the greeter.v1 schema. The companion
// greeter_grpc.pb.go carries the load-bearing import line +
// GreeterServer interface declaration the proto.StubArtifacts scan
// matches.
package greeter

type GreeterRequest struct {
	Name string
}

type GreeterReply struct {
	Message string
}
