// SPDX-License-Identifier: MIT
package writer

import (
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/cbip-solutions/hades-system/internal/migrate/mapping"
)

var ErrUnknownPermissionStrict = errors.New("doctrine_toml: unmappable permission in strict mode (invariant no silent drop)")

// writeDoctrineTOML emits ~/.config/hades-system/doctrines/imported-from-claude-code.toml
// per design contract:1 preservation of allow/deny per
// invariant: every input permission entry MUST appear verbatim in the
// output [capa_firewall] block.
func writeDoctrineTOML(path string, e mapping.PlanEntry) error {
	var src struct {
		Allow []string          `json:"allow"`
		Deny  []string          `json:"deny"`
		Env   map[string]string `json:"env"`
	}
	if err := json.Unmarshal(e.BodyBytes, &src); err != nil {
		return fmt.Errorf("doctrine_toml: parse plan payload: %w", err)
	}
	tiers := map[string]string{}
	for _, perm := range src.Allow {
		tiers[perm] = classifyTier(perm)
	}
	for _, perm := range src.Deny {
		tiers[perm] = classifyTier(perm)
	}
	body := renderDoctrineTOML(src.Allow, src.Deny, tiers, src.Env, e.SourcePath)
	return atomicWriteFile(path, body, 0o644)
}

func ImportDoctrineStrict(allow, deny []string) error {
	for _, p := range allow {
		if classifyTierStrict(p) == "" {
			return fmt.Errorf("%w: %s", ErrUnknownPermissionStrict, p)
		}
	}
	for _, p := range deny {
		if classifyTierStrict(p) == "" {
			return fmt.Errorf("%w: %s", ErrUnknownPermissionStrict, p)
		}
	}
	return nil
}

func UnmappedPermissions(allow, deny []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, p := range allow {
		if classifyTierStrict(p) == "" && !seen[p] {
			seen[p] = true
			out = append(out, p)
		}
	}
	for _, p := range deny {
		if classifyTierStrict(p) == "" && !seen[p] {
			seen[p] = true
			out = append(out, p)
		}
	}
	return out
}

func classifyTier(perm string) string {
	tier := classifyTierStrict(perm)
	if tier == "" {
		return "medium"
	}
	return tier
}

func classifyTierStrict(perm string) string {
	p := strings.ToLower(perm)

	if strings.HasPrefix(p, "filesystem.write") ||
		strings.HasPrefix(p, "postgres.execute") ||
		strings.HasPrefix(p, "github.write") ||
		strings.HasPrefix(p, "mysql.write") ||
		strings.HasPrefix(p, "write(") {
		return "high"
	}

	if strings.HasPrefix(p, "playwright") ||
		strings.HasPrefix(p, "openapi") ||
		strings.HasPrefix(p, "graphql") ||
		strings.HasPrefix(p, "sentry") ||
		strings.HasPrefix(p, "webfetch") ||
		strings.HasPrefix(p, "linear") {
		return "medium"
	}

	if strings.HasPrefix(p, "sequential") ||
		strings.HasPrefix(p, "memory") ||
		strings.HasPrefix(p, "gitnexus") ||
		strings.HasPrefix(p, "read(") ||
		strings.HasPrefix(p, "bash(") {
		return "low"
	}
	return ""
}

func renderDoctrineTOML(allow, deny []string, tiers map[string]string, env map[string]string, sourcePath string) []byte {
	sb := strings.Builder{}
	sb.WriteString("# Generated by `hades migrate claude-code`.\n")
	sb.WriteString("# 1:1 preservation per invariant. Source: ")
	sb.WriteString(sourcePath)
	sb.WriteString("\n\n")
	sb.WriteString("schema_version = \"1.0\"\n")
	sb.WriteString("name = \"imported-from-claude-code\"\n")
	sb.WriteString("inherits_from = \"max-scope\"\n")
	sb.WriteString("description = \"Imported from ~/local agent config/settings.json permissions.\"\n\n")
	sb.WriteString("[capa_firewall]\n")
	sb.WriteString("allow = [\n")
	for _, p := range allow {
		sb.WriteString("  \"")
		sb.WriteString(strings.ReplaceAll(p, `"`, `\"`))
		sb.WriteString("\",\n")
	}
	sb.WriteString("]\n")
	sb.WriteString("deny = [\n")
	for _, p := range deny {
		sb.WriteString("  \"")
		sb.WriteString(strings.ReplaceAll(p, `"`, `\"`))
		sb.WriteString("\",\n")
	}
	sb.WriteString("]\n\n")
	sb.WriteString("[capa_firewall.tiers]\n")
	keys := make([]string, 0, len(tiers))
	for k := range tiers {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		sb.WriteString("\"")
		sb.WriteString(strings.ReplaceAll(k, `"`, `\"`))
		sb.WriteString("\" = \"")
		sb.WriteString(tiers[k])
		sb.WriteString("\"\n")
	}
	if len(env) > 0 {
		sb.WriteString("\n[env]\n")
		envKeys := make([]string, 0, len(env))
		for k := range env {
			envKeys = append(envKeys, k)
		}
		sort.Strings(envKeys)
		for _, k := range envKeys {
			sb.WriteString(k)
			sb.WriteString(" = \"")
			sb.WriteString(strings.ReplaceAll(env[k], `"`, `\"`))
			sb.WriteString("\"\n")
		}
	}
	return []byte(sb.String())
}
