// SPDX-License-Identifier: MIT
package writer

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/cbip-solutions/hades-system/internal/migrate/mapping"
)

func writeHermesConfig(path string, e mapping.PlanEntry) error {
	body := renderHermesConfig(e)
	return atomicWriteFile(path, body, 0o644)
}

type hermesConfigPayload struct {
	Model      string                          `json:"model"`
	MCPServers map[string]hermesMCPServerEntry `json:"mcpServers"`
}

type hermesMCPServerEntry struct {
	Command string            `json:"command"`
	Args    []string          `json:"args"`
	Env     map[string]string `json:"env"`
}

const defaultModel = "claude-opus-4-7-1m"

func renderHermesConfig(e mapping.PlanEntry) []byte {
	payload := decodeHermesPayload(e.BodyBytes)
	model := payload.Model
	if model == "" {
		model = defaultModel
	}
	sb := strings.Builder{}
	sb.WriteString("# Generated by `hades migrate claude-code`.\n")
	sb.WriteString("# imported-from: claude-code\n\n")
	sb.WriteString("default_provider:\n")
	sb.WriteString("  name: anthropic\n")
	fmt.Fprintf(&sb, "  model: %s\n", yamlScalarString(model))
	sb.WriteString("\n")
	sb.WriteString("mcp_servers:\n")
	for _, line := range renderMCPServersBlock(payload.MCPServers) {
		sb.WriteString(line)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "# Raw source: %s\n", e.SourcePath)
	return []byte(sb.String())
}

func decodeHermesPayload(body []byte) hermesConfigPayload {
	var p hermesConfigPayload
	if len(body) == 0 {
		return p
	}
	_ = json.Unmarshal(body, &p)
	return p
}

func renderMCPServersBlock(operator map[string]hermesMCPServerEntry) []string {
	var lines []string
	keys := make([]string, 0, len(operator))
	for k := range operator {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		v := operator[k]
		lines = append(lines, fmt.Sprintf("  %s:", yamlMapKey(k)))
		lines = append(lines, fmt.Sprintf("    command: %s", yamlScalarString(v.Command)))
		lines = append(lines, fmt.Sprintf("    args: %s", yamlStringSlice(v.Args)))
		if len(v.Env) > 0 {
			lines = append(lines, "    env:")
			envKeys := make([]string, 0, len(v.Env))
			for ek := range v.Env {
				envKeys = append(envKeys, ek)
			}
			sort.Strings(envKeys)
			for _, ek := range envKeys {
				lines = append(lines, fmt.Sprintf("      %s: %s",
					yamlMapKey(ek), yamlScalarString(v.Env[ek])))
			}
		}
	}

	if _, ok := operator["hades-system"]; !ok {
		lines = append(lines,
			"  hades-system:",
			"    transport: http",
			"    url: http://unix/v1/mcpgateway",
			"    socket: /tmp/hades-system.sock",
		)
	} else {
		lines = append(lines, " # hades-system gateway entry collided with operator config; operator wins.")
	}
	return lines
}

func yamlScalarString(s string) string {
	if s == "" {
		return "\"\""
	}
	if needsYAMLQuote(s) {
		return strconv.Quote(s)
	}
	return s
}

func yamlMapKey(s string) string {
	if s == "" {
		return "\"\""
	}
	if needsYAMLQuote(s) {
		return strconv.Quote(s)
	}
	return s
}

func yamlStringSlice(xs []string) string {
	if len(xs) == 0 {
		return "[]"
	}
	parts := make([]string, len(xs))
	for i, v := range xs {
		parts[i] = yamlScalarString(v)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// needsYAMLQuote returns true if a string MUST be quoted to round-trip
// safely through a YAML parser.
func needsYAMLQuote(s string) bool {
	if s == "" {
		return true
	}

	low := strings.ToLower(s)
	switch low {
	case "true", "false", "yes", "no", "on", "off", "null", "~":
		return true
	}

	if isYAMLNumericLike(s) {
		return true
	}

	for _, r := range s {
		switch r {
		case ':', '#', '&', '*', '!', '|', '>', '\'', '"', '%', '`',
			'\n', '\r', '\t', '@', '[', ']', '{', '}', ',':
			return true
		}
		if r < 0x20 || r == 0x7f {
			return true
		}
	}

	switch s[0] {
	case ' ', '\t', '-', '?', '[', ']', '{', '}', ',':
		return true
	}

	if last := s[len(s)-1]; last == ' ' || last == '\t' {
		return true
	}
	return false
}

func isYAMLNumericLike(s string) bool {

	if len(s) == 0 {
		return false
	}
	first := s[0]
	if !(first >= '0' && first <= '9') && first != '+' && first != '-' && first != '.' {
		return false
	}
	hasDigit := false
	for _, r := range s {
		switch {
		case r >= '0' && r <= '9':
			hasDigit = true
		case r == '.', r == 'e', r == 'E', r == '+', r == '-', r == '_', r == 'x', r == 'X',
			(r >= 'a' && r <= 'f'), (r >= 'A' && r <= 'F'):

		default:
			return false
		}
	}
	return hasDigit
}

// RenderMCPServersBlockForCompliance is an EXPORTED test-only accessor to
// renderMCPServersBlock so the invariant compliance test (in
// tests/compliance/) can verify the runtime output without owning the
// hermesMCPServerEntry type internals. The compliance test passes nil
// (no operator overrides) to exercise the gateway-default emission path.
//
// DO NOT call from production code — use renderMCPServersBlock directly
// when inside this package. This wrapper exists solely so the cross-package
// compliance gate has a stable surface.
func RenderMCPServersBlockForCompliance(operator map[string]hermesMCPServerEntry) []string {
	return renderMCPServersBlock(operator)
}
