package writer

import (
	"strings"
	"testing"
)

func TestRenderInitPy_Empty(t *testing.T) {
	t.Parallel()
	body := renderInitPy(nil)
	s := string(body)
	if !strings.Contains(s, "def register(ctx):") {
		t.Errorf("missing register def: %s", s)
	}
	if !strings.Contains(s, "pass") {
		t.Errorf("empty body must be `pass`: %s", s)
	}
}

func TestRenderInitPy_Deterministic(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_skill("b", "skills/b/SKILL.md", description="b")`,
		`ctx.register_skill("a", "skills/a/SKILL.md", description="a")`,
	}
	a := renderInitPy(calls)
	b := renderInitPy(calls)
	if string(a) != string(b) {
		t.Errorf("non-deterministic")
	}

	idxA := strings.Index(string(a), `register_skill("a"`)
	idxB := strings.Index(string(a), `register_skill("b"`)
	if idxA == -1 || idxB == -1 || idxA > idxB {
		t.Errorf("calls not sorted lex: %s", a)
	}
}

func TestRenderInitPy_HeaderPresent(t *testing.T) {
	t.Parallel()
	body := renderInitPy([]string{`ctx.register_skill("x", "y", description="z")`})
	if !strings.Contains(string(body), "Generated by") {
		t.Errorf("missing generator header: %s", body)
	}
	if !strings.Contains(string(body), "--force to regenerate") {
		t.Errorf("missing regen hint")
	}
}

func TestRenderInitPy_RegisterImportsHandlers(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_command("brainstorm", handler=brainstorm_handler, description="research-first brainstorm")`,
		`ctx.register_command("write-plan", handler=write_plan_handler, description="TDD plan writer")`,
		`ctx.register_skill("brainstorm", "skills/brainstorm/SKILL.md", description="brainstorm skill")`,
	}
	body := renderInitPy(calls)

	bodyStr := string(body)
	mustContain := []string{
		"from .commands.brainstorm import brainstorm_handler",
		"from .commands.write_plan import write_plan_handler",
		`ctx.register_command("hades:brainstorm", handler=brainstorm_handler`,
		`ctx.register_command("hades:write-plan", handler=write_plan_handler`,
		`ctx.register_skill("brainstorm",`,
	}
	for _, m := range mustContain {
		if !strings.Contains(bodyStr, m) {
			t.Errorf("rendered __init__.py missing %q\nbody:\n%s", m, bodyStr)
		}
	}

	pyImportRegisterAgainstStubCtx(t, body, []string{"brainstorm", "write_plan"})
}

func TestRenderInitPy_NoImportsWhenNoHandlerCalls(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_skill("alpha", "skills/alpha/SKILL.md", description="a")`,
		`ctx.register_skill("beta",  "skills/beta/SKILL.md",  description="b")`,
	}
	body := renderInitPy(calls)
	bodyStr := string(body)
	if strings.Contains(bodyStr, "from .commands") {
		t.Errorf("rendered __init__.py emitted spurious `from .commands` line for skill-only input:\n%s", bodyStr)
	}

	pyImportRegisterAgainstStubCtx(t, body, nil)
}

func TestRenderInitPy_HandlerImportsDedupe(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_command("hades:doctrine", handler=doctrine_handler, description="show doctrine")`,
		`ctx.register_command("hades:doctrine-override", handler=doctrine_handler, description="override doctrine")`,
	}
	body := renderInitPy(calls)
	bodyStr := string(body)
	count := strings.Count(bodyStr, "from .commands.doctrine import doctrine_handler")
	if count != 1 {
		t.Errorf("expected exactly 1 import line for doctrine_handler, got %d\nbody:\n%s", count, bodyStr)
	}
}

func TestRenderInitPy_NormalizesBareToHadesNamespace(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_command("brainstorm", handler=brainstorm_handler, description="x")`,
	}
	body := string(renderInitPy(calls))
	if !strings.Contains(body, `ctx.register_command("hades:brainstorm"`) {
		t.Errorf("expected bare 'brainstorm' to be rewritten to 'hades:brainstorm' in output\nbody:\n%s", body)
	}
	if strings.Contains(body, `ctx.register_command("brainstorm"`) {
		t.Errorf("expected ORIGINAL bare 'brainstorm' to be absent from output (rewrite must be complete)\nbody:\n%s", body)
	}
}

// TestRenderInitPy_NormalizesZenSwarmToHadesNamespace — Plan 18b Phase B B-7.
// Legacy `zen-swarm:<name>` first positional args MUST be rewritten to
// `hades:<name>` in the emitted output. Spec §Q4 hard cutover.
func TestRenderInitPy_NormalizesZenSwarmToHadesNamespace(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_command("zen-swarm:start", handler=handle_start, description="x")`,
	}
	body := string(renderInitPy(calls))
	if !strings.Contains(body, `ctx.register_command("hades:start"`) {
		t.Errorf("expected 'zen-swarm:start' to be rewritten to 'hades:start' in output\nbody:\n%s", body)
	}
	if strings.Contains(body, `"zen-swarm:`) {
		t.Errorf("expected legacy 'zen-swarm:' prefix to be absent from output\nbody:\n%s", body)
	}
}

// TestRenderInitPy_PreservesHadesNamespaceIdempotent — Plan 18b Phase B B-7.
// Input calls already correctly under `hades:` namespace MUST be emitted
// unchanged (rewriter is idempotent).
func TestRenderInitPy_PreservesHadesNamespaceIdempotent(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_command("hades:write-plan", handler=write_plan_handler, description="x")`,
	}
	body := string(renderInitPy(calls))
	if !strings.Contains(body, `ctx.register_command("hades:write-plan"`) {
		t.Errorf("expected 'hades:write-plan' to be PRESERVED in output (idempotent)\nbody:\n%s", body)
	}

	if strings.Contains(body, `"hades:hades:`) {
		t.Errorf("DOUBLE-PREFIXING bug: 'hades:hades:' appeared in output\nbody:\n%s", body)
	}
}

// TestRenderInitPy_NamespaceRewriteLeavesNonRegisterCommandUntouched —
// The rewriter MUST only touch register_command first positional args.
// register_skill calls (which take a name string in the first positional
// too) MUST NOT be rewritten — skill names live in a separate namespace
// per master §"Cross-phase type discipline".
func TestRenderInitPy_NamespaceRewriteLeavesNonRegisterCommandUntouched(t *testing.T) {
	t.Parallel()
	calls := []string{
		`ctx.register_skill("zen-swarm", "skills/zen-swarm/SKILL.md", description="x")`,
		`ctx.register_skill("brainstorm", "skills/brainstorm/SKILL.md", description="x")`,
	}
	body := string(renderInitPy(calls))
	if !strings.Contains(body, `ctx.register_skill("zen-swarm"`) {
		t.Errorf("register_skill 'zen-swarm' must be preserved (not rewritten)\nbody:\n%s", body)
	}
	if !strings.Contains(body, `ctx.register_skill("brainstorm"`) {
		t.Errorf("register_skill 'brainstorm' must be preserved (not rewritten)\nbody:\n%s", body)
	}
	if strings.Contains(body, `register_skill("hades:`) {
		t.Errorf("register_skill names must NOT be hades-prefixed (cross-phase type discipline)\nbody:\n%s", body)
	}
}
