// SPDX-License-Identifier: MIT
package writer

import (
	"regexp"
	"sort"
	"strings"
)

// renderInitPy generates plugin/hades/__init__.py with a register(ctx)
// function containing the accumulated ctx.register_skill/command/hook calls
// per spec §8.5 PluginManifest + Hermes spike §5-6. Deterministic: calls
// are sorted lexicographically before emission; imports auto-derived from
// any `handler=<X>_handler` references in the calls slice.
//
// Bug-1 invariant: the emitted register(ctx) body MUST import every
// `<X>_handler` identifier it references, or plugin import raises
// NameError + every subsequent register_skill call is skipped. Each
// `handler=<X>_handler` reference therefore produces a matching
// `from .commands.<X> import <X>_handler` import line above the def.
//
// Handler module names are emitted underscored (Python identifier safe).
// The write_command.go fix ensures the on-disk filenames also use
// underscores, so the imports resolve.
//
// normalizeSlashNamespace is applied to all calls before processing.
// It rewrites the first positional arg of every ctx.register_command(...)
// call to use the `hades:` namespace prefix — bare names become
// `hades:<name>`, `zen-swarm:<name>` becomes `hades:<name>`, and
// already-`hades:` names are left unchanged (idempotent).
// register_skill calls are NOT touched (skill names live in a separate
// namespace per spec §"Cross-phase type discipline").
func renderInitPy(calls []string) []byte {

	calls = normalizeSlashNamespace(calls)

	sb := strings.Builder{}
	sb.WriteString("# Generated by `zen migrate claude-code`.\n")
	sb.WriteString("# Do not edit by hand; re-run with --force to regenerate.\n\n")

	handlers := extractHandlerNames(calls)
	for _, h := range handlers {
		sb.WriteString("from .commands.")
		sb.WriteString(h)
		sb.WriteString(" import ")
		sb.WriteString(h)
		sb.WriteString("_handler\n")
	}
	if len(handlers) > 0 {
		sb.WriteString("\n")
	}

	sb.WriteString("def register(ctx):\n")
	if len(calls) == 0 {
		sb.WriteString("    pass\n")
		return []byte(sb.String())
	}
	sorted := append([]string{}, calls...)
	sort.Strings(sorted)
	for _, c := range sorted {
		sb.WriteString("    ")
		sb.WriteString(c)
		sb.WriteString("\n")
	}
	return []byte(sb.String())
}

var registerCommandFirstArgPattern = regexp.MustCompile(
	`(ctx\.register_command\(\s*")(zen-swarm:)?([a-zA-Z][a-zA-Z0-9_:-]*)`,
)

func normalizeSlashNamespace(calls []string) []string {
	out := make([]string, len(calls))
	for i, c := range calls {
		out[i] = registerCommandFirstArgPattern.ReplaceAllStringFunc(c, func(match string) string {

			sub := registerCommandFirstArgPattern.FindStringSubmatch(match)
			if sub == nil {
				return match
			}
			prefix := sub[1]

			slug := sub[3]

			if strings.HasPrefix(slug, "hades:") {
				return match
			}

			return prefix + "hades:" + slug
		})
	}
	return out
}

var handlerRefPattern = regexp.MustCompile(`handler=([A-Za-z_][A-Za-z0-9_]*)_handler\b`)

func extractHandlerNames(calls []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, c := range calls {
		for _, m := range handlerRefPattern.FindAllStringSubmatch(c, -1) {
			name := m[1]
			if !seen[name] {
				seen[name] = true
				out = append(out, name)
			}
		}
	}
	sort.Strings(out)
	return out
}
