// SPDX-License-Identifier: MIT
package writer

import (
	"fmt"
	"strings"

	"github.com/cbip-solutions/hades-system/internal/migrate/mapping"
)

func renderPluginYAML(plan *mapping.Plan) []byte {
	skillCount, cmdCount, hookCount := 0, 0, 0
	for _, e := range plan.Entries {
		switch e.Kind {
		case mapping.EntryKindSkill:
			skillCount++
		case mapping.EntryKindCommand:
			cmdCount++
		case mapping.EntryKindHook:
			hookCount++
		}
	}
	sb := strings.Builder{}
	sb.WriteString("# Generated by `hades migrate claude-code`.\n")
	sb.WriteString("# imported-from: claude-code\n")
	sb.WriteString("name: hades-system\n")
	sb.WriteString("version: 0.0.1\n")
	sb.WriteString("description: Imported from a Claude Code installation via `hades migrate claude-code`.\n")
	sb.WriteString("license: imported\n")
	sb.WriteString("metadata:\n")
	sb.WriteString("  hades-system:\n")
	sb.WriteString(fmt.Sprintf("    imported_skill_count: %d\n", skillCount))
	sb.WriteString(fmt.Sprintf("    imported_command_count: %d\n", cmdCount))
	sb.WriteString(fmt.Sprintf("    imported_hook_count: %d\n", hookCount))
	return []byte(sb.String())
}
