// SPDX-License-Identifier: MIT
// Package cli — providers.go
//
// `zen providers` subcommands manage the LLM provider roster. release
// replaces the release notImplementedSubcommand stubs with real
// commands. `list` + `init` (this file) read/write the config files
// directly; `verify` / `rotate` / `add` / `setup` (providers_extra.go,
// Task 17) touch the Keychain.
//
// configDir resolution: ~/.config/zen-swarm/providers/ — the same
// location cmd/zen-swarm-ctld reads providers.toml from. The
// configDirFunc seam lets tests point at a t.TempDir().
package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"github.com/cbip-solutions/hades-system/internal/config"
	ierrors "github.com/cbip-solutions/hades-system/internal/errors"
	"github.com/cbip-solutions/hades-system/internal/providers"
)

type configDirFunc func() string

func defaultProviderConfigDir() string {
	return filepath.Join(os.Getenv("HOME"), ".config", "zen-swarm", "providers")
}

func NewProvidersCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "providers",
		Short: "LLM provider configuration",
	}
	cmd.AddCommand(newProvidersListCmd(defaultProviderConfigDir))
	cmd.AddCommand(newProvidersInitCmd(defaultProviderConfigDir))
	cmd.AddCommand(newProvidersVerifyCmd(defaultProviderConfigDir))
	cmd.AddCommand(newProvidersRotateCmd(defaultProviderConfigDir))
	cmd.AddCommand(newProvidersAddCmd(defaultProviderConfigDir))
	cmd.AddCommand(newProvidersSetupCmd(defaultProviderConfigDir))
	return cmd
}

func newProvidersListCmd(dir configDirFunc) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List configured providers",
		RunE: func(cmd *cobra.Command, _ []string) error {
			path := filepath.Join(dir(), "providers.toml")
			declared, err := config.LoadProviders(path)
			if err != nil {
				if errors.Is(err, os.ErrNotExist) {
					fmt.Fprintln(cmd.OutOrStdout(),
						"no providers configured — run `zen providers init` to materialize the roster")
					return nil
				}
				return ierrors.Wrap(ierrors.Code("daemon.unreachable"), fmt.Errorf("providers list: %w", err))
			}
			tw := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 2, 2, ' ', 0)
			fmt.Fprintln(tw, "NAME\tTYPE\tFAMILY\tTIER\tMODEL")
			for _, p := range declared {
				tier, perr := providers.ParseTier(p.Type)
				tierStr := tier.String()
				if perr != nil {
					tierStr = "?"
				}
				fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%s\n", p.Name, p.Type, p.Family, tierStr, p.Model)
			}
			return tw.Flush()
		},
	}
}

func newProvidersInitCmd(dir configDirFunc) *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Materialize providers.toml + profiles.toml from the built-in roster",
		RunE: func(cmd *cobra.Command, _ []string) error {
			d := dir()
			if err := os.MkdirAll(d, 0o755); err != nil {
				return ierrors.Wrap(ierrors.Code("internal-uncaught"), fmt.Errorf("providers init: mkdir %s: %w", d, err))
			}
			providersPath := filepath.Join(d, "providers.toml")
			profilesPath := filepath.Join(d, "profiles.toml")
			if _, err := os.Stat(providersPath); err == nil {
				return ierrors.Wrap(ierrors.Code("cli.arg-validation-fail"), fmt.Errorf("providers init: %s already exists (refusing to overwrite operator edits)", providersPath))
			}
			if err := os.WriteFile(providersPath, []byte(rosterProvidersTOML), 0o644); err != nil {
				return ierrors.Wrap(ierrors.Code("wizard.migrate-incomplete"), fmt.Errorf("providers init: write providers.toml: %w", err))
			}
			if err := os.WriteFile(profilesPath, []byte(rosterProfilesTOML), 0o644); err != nil {
				return ierrors.Wrap(ierrors.Code("wizard.migrate-incomplete"), fmt.Errorf("providers init: write profiles.toml: %w", err))
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\nwrote %s\n", providersPath, profilesPath)
			fmt.Fprintln(cmd.OutOrStdout(),
				"next: fill in each [[providers]] endpoint, then provision Keychain keys "+
					"(security add-generic-password -U -s \"zen-swarm/<provider>\" -a \"zen-swarm\" -w \"<key>\")")
			return nil
		},
	}
}

const rosterProvidersTOML = `# HADES providers.toml — LLM backend declarations.
# Generated by 'zen providers init'. Edit endpoints + provision Keychain keys.

[[providers]]
name             = "anthropic-paygo"
type             = "anthropic-paygo"
endpoint         = "https://api.anthropic.com"
model            = "claude-haiku-4-5"
family           = "anthropic"
api_key_keychain = "zen-swarm/anthropic-paygo"

[[providers]]
name             = "gemini-pro"
type             = "gemini"
endpoint         = "https://generativelanguage.googleapis.com"
model            = "gemini-2.0-pro"
family           = "gemini"
api_key_keychain = "zen-swarm/google-ai"

[[providers]]
name             = "gemini-flash"
type             = "gemini"
endpoint         = "https://generativelanguage.googleapis.com"
model            = "gemini-2.0-flash"
family           = "gemini"
api_key_keychain = "zen-swarm/google-ai"

[[providers]]
name             = "deepseek-direct"
type             = "openai-compat"
endpoint         = "https://api.deepseek.com"
model            = "deepseek-chat"
family           = "deepseek"
api_key_keychain = "zen-swarm/deepseek"

[[providers]]
name             = "moonshot-kimi"
type             = "openai-compat"
endpoint         = "https://api.moonshot.cn"
model            = "moonshot-v1-128k"
family           = "moonshot"
api_key_keychain = "zen-swarm/moonshot"

[[providers]]
name             = "zhipu-glm-flash"
type             = "openai-compat"
endpoint         = "https://open.bigmodel.cn/api/paas"
model            = "glm-4-flash"
family           = "zhipu"
api_key_keychain = "zen-swarm/zhipu"

[[providers]]
name             = "siliconflow-deepseek"
type             = "openai-compat"
endpoint         = "https://api.siliconflow.cn"
model            = "deepseek-ai/DeepSeek-V3"
family           = "deepseek"
api_key_keychain = "zen-swarm/siliconflow"

[[providers]]
name             = "openrouter-deepseek"
type             = "openai-compat"
endpoint         = "https://openrouter.ai/api"
model            = "deepseek/deepseek-chat"
family           = "deepseek"
api_key_keychain = "zen-swarm/openrouter"

[[providers]]
name             = "openrouter-kimi"
type             = "openai-compat"
endpoint         = "https://openrouter.ai/api"
model            = "moonshotai/kimi-k2"
family           = "moonshot"
api_key_keychain = "zen-swarm/openrouter"

[[providers]]
name             = "openrouter-glm"
type             = "openai-compat"
endpoint         = "https://openrouter.ai/api"
model            = "zhipu/glm-4-flash"
family           = "zhipu"
api_key_keychain = "zen-swarm/openrouter"

[[providers]]
name     = "ollama-qwen-coder"
type     = "ollama"
endpoint = "http://localhost:11434"
model    = "qwen2.5-coder:32b"
family   = "qwen"
`

const rosterProfilesTOML = `# HADES profiles.toml — role -> ordered provider cascade.
# Generated by 'zen providers init'. Each cascade names providers.toml entries.

[profiles.orchestrator]
description = "Roster S/S' — top-level planner"
cascade     = ["bypass", "gemini-pro"]

[profiles.worker-code]
description = "Roster A1a — DeepSeek-V3 code worker"
cascade     = ["deepseek-direct", "siliconflow-deepseek", "openrouter-deepseek"]

[profiles.worker-reasoning]
description = "Roster A1b — Kimi K2 reasoning worker"
cascade     = ["moonshot-kimi", "openrouter-kimi"]

[profiles.tactical]
description = "Roster B — fast tactical tier"
cascade     = ["gemini-flash", "zhipu-glm-flash", "openrouter-glm"]

[profiles.local-code]
description = "Roster C2 — local Ollama coder"
cascade     = ["ollama-qwen-coder"]
`
