-- Migration 063: schedules + schedule_history (HADES design release track Task D-1).
--
-- Hosts the durable scheduler substrate: Routine + Task + Loop schedules
-- (3-tier per spec §1 Q8 D) plus the per-fire outcome ledger driving
-- `hades schedule history`. release track ships only the schema (this file) and
-- the Go-side CRUD primitives (internal/store/schedules.go); the
-- internal/scheduler/ package and its scheduleradapter bridge land in
-- D-2..D-12.
--
-- Drift note (HADES design release track):
--   The original master plan §"Migration numbering coordination"
--   reserved slot 059 for release track schedules table under an
--   execution-order sequence A→C→B→D→E. Reality at HEAD on 2026-05-07:
--     - 057 taken by release track (projects_alias + path_history)
--     - 060 taken by release track (priority_overrides; joint payload split)
--     - 062 taken by release track (tmux_session_state)
--     - schemaVersion = 26 entering release track
--   release track therefore picks 063 — the next free number on the
--   daemon.db schema chain. Slot 059 is reserved for release track inbox
--   storage, slot 061 is reserved for release track knowledge-index DB
--   (separate SQLite file, no daemon.db schemaVersion bump).
--   schemaVersion bump path: 26 (release track) → 27 (this migration).
--
-- Boundary (invariant release track slice):
--   internal/scheduler/* MUST NEVER import internal/store; the daemon
--   adapter (internal/daemon/scheduleradapter/) is the ONLY package
--   permitted to bridge scheduler value types to *store.Store via the
--   CRUD primitives in internal/store/schedules.go. release track
--   inv_hades_122 compliance test extends to enforce this on HADES design
--   packages.
--
-- Boundary (invariant / invariant release track slice):
--   The schedules table itself stores no LLM-call surface; it is the
--   trigger substrate. scheduler.Fire orchestrates dispatch via the
--   dispatcher.Client interface so this table is single-egress-aligned
--   by abstraction (fired actions cross internal/daemon/dispatcher/
--   never internal/providers/ direct).
--
-- Compile-time invariants surfaced:
--   - invariant (jitter deterministic) — enforced in app code via
--     scheduler.ComputeJitter(routineID, period); the schedules.id
--     column is the canonical hash input.
--   - invariant (per-doctrine miss policy + rate-limit) — enforced
--     in app code via scheduler.DoctrineMissPolicy(d) matrix and
--     scheduler.RateLimiter; the miss_policy column is CHECK-
--     constrained so a corrupted INSERT fails fast.
--
-- ----------------------------------------------------------------------------
-- schedules table
-- ----------------------------------------------------------------------------
--
-- One row per Routine, Task, or Loop schedule. UUIDv7-keyed (TEXT PK
-- so the canonical id is content-addressable on the wire and across
-- backups). All time columns store UTC unix seconds (per invariant);
-- the Go layer translates to time.Time, mapping NULL to zero-value.
--
-- Constraints:
--
--   - id TEXT PRIMARY KEY: UUIDv7 generated by the daemon; PRIMARY KEY
--                          implicit UNIQUE blocks duplicate Insert.
--                          The Go layer translates a PK violation into
--                          ErrDuplicateScheduleID (typed sentinel)
--                          plus driver-stable
--                          sqlite3.CONSTRAINT_PRIMARYKEY (defense in
--                          depth — same predicate in two places).
--
--   - tier INTEGER NOT NULL CHECK (tier IN (0,1,2)):
--                          0=Routine, 1=Task, 2=Loop. The three-tier
--                          taxonomy is load-bearing per spec §1 Q8 D.
--                          The Go-side validateScheduleTier rejects
--                          out-of-range values BEFORE the SQL CHECK
--                          fires (better error message + faster
--                          short-circuit).
--
--   - project_alias TEXT NOT NULL: release track projectctx alias. Plain text
--                          — NOT a FK to projects_alias.alias.
--                          Schedules are forensic-relevant beyond
--                          project lifecycle (`hades day` digest reads
--                          archived schedule outcomes); coupling
--                          lifecycle via FK CASCADE would silently lose
--                          audit-relevant rows. Same rationale as
--                          priority_overrides (migration 060) and
--                          tmux_session_state (migration 062).
--
--   - action TEXT NOT NULL: semantic action key (e.g. `morning-brief`,
--                          `cost-sweep`, `hra-l2-tick`); the HADES design
--                          dispatcher resolves this to a TaskInput via
--                          routing rules (HADES design+ extends).
--
--   - trigger_type INTEGER NOT NULL CHECK (trigger_type IN (0,1,2)):
--                          0=Cron, 1=HTTP, 2=GitPoll. Three trigger
--                          types verbatim Anthropic Routines per spec
--                          §1 Q8.
--
--   - trigger_config TEXT NOT NULL: JSON blob.
--                          trigger_type=Cron → {"cron_expr":"0 8 * * 1-5"}
--                          trigger_type=HTTP → {"endpoint":".../fire", ...}
--                          trigger_type=GitPoll → {"repo":"…","branch":"…","cursor":"…"}
--                          The Go-side validateScheduleTriggerConfig
--                          rejects empty / malformed JSON before the
--                          SQL store; the schema layer is content-blind
--                          on the JSON shape (the trigger_type column +
--                          Go-side decoder enforce the union).
--
--   - miss_policy INTEGER NOT NULL CHECK (miss_policy IN (0,1,2,3)):
--                          0=Skip, 1=CatchUpBounded, 2=Coalesce,
--                          3=NotifyOnly. Per-doctrine miss-policy
--                          matrix lives in scheduler.DoctrineMissPolicy
--                          (invariant); CHECK is the floor.
--
--   - miss_lookback_seconds INTEGER NOT NULL DEFAULT 604800:
--                          7 days; configurable per routine via
--                          --miss-lookback. The bounded catch-up policy
--                          (max-scope) uses this as the upper bound on
--                          replay; Skip / NotifyOnly ignore.
--
--   - coalesce_window_seconds INTEGER NOT NULL DEFAULT 0:
--                          0 means no coalescing. Aggregate routines
--                          that prefer "single fire with backfill
--                          window" pass a non-zero value here so
--                          scheduler.Coalesce returns a single fire +
--                          BackfillWindow argument.
--
--   - last_run_at_unix INTEGER: NULL means never run. UTC unix seconds.
--                          Updated by scheduler.Fire on success.
--
--   - next_run_at_unix INTEGER: NULL means disabled or pending recompute.
--                          UTC unix seconds. The scheduler tick query
--                          (idx_schedules_due) reads WHERE
--                          next_run_at_unix <= now AND status = 0.
--
--   - status INTEGER NOT NULL DEFAULT 0 CHECK (status IN (0,1,2)):
--                          0=Enabled, 1=Disabled, 2=Failed. Failed
--                          rows survive for forensic analysis (`hades
--                          schedule history`); operator-driven
--                          re-enable transitions Failed→Enabled with
--                          an audit event.
--
--   - created_at_unix INTEGER NOT NULL: INSERT timestamp; ORDER BY
--                          created_at_unix DESC drives `hades schedule
--                          list` for newest-first ordering.
--
--   - bearer_token_hash TEXT: SHA-256 hex of HTTP trigger token; NULL
--                          for non-HTTP triggers. The raw token NEVER
--                          persists. The httptrigger handler hashes
--                          incoming Authorization: Bearer <token>
--                          values + constant-time-compares; mismatch
--                          → 401 + audit emission.
--
-- Index strategy:
--
--   - PRIMARY KEY(id) is implicitly indexed; Get bypasses any other
--     scan path.
--
--   - idx_schedules_due (status, next_run_at_unix) WHERE status = 0:
--     the scheduler tick (release track) runs every 10s per spec §3.6;
--     the partial index keeps the scan in-index without touching
--     disabled or failed rows, accelerating the common case (most
--     rows enabled, a few due at any time).
--
--   - idx_schedules_project_alias accelerates `hades schedule list
--     --project=<alias>` and the audit query path (`hades audit log
--     --schedule-project=...`).

CREATE TABLE IF NOT EXISTS schedules (
    id                       TEXT PRIMARY KEY,
    tier                     INTEGER NOT NULL CHECK (tier IN (0, 1, 2)),                  -- 0=Routine, 1=Task, 2=Loop
    project_alias            TEXT NOT NULL,
    action                   TEXT NOT NULL,
    trigger_type             INTEGER NOT NULL CHECK (trigger_type IN (0, 1, 2)),          -- 0=Cron, 1=HTTP, 2=GitPoll
    trigger_config           TEXT NOT NULL,                                               -- JSON blob (Cron / HTTP / GitPoll union)
    miss_policy              INTEGER NOT NULL CHECK (miss_policy IN (0, 1, 2, 3)),        -- 0=Skip, 1=CatchUpBounded, 2=Coalesce, 3=NotifyOnly
    miss_lookback_seconds    INTEGER NOT NULL DEFAULT 604800,                             -- 7 days default
    coalesce_window_seconds  INTEGER NOT NULL DEFAULT 0,                                  -- 0 = no coalescing
    last_run_at_unix         INTEGER,                                                     -- NULL = never run
    next_run_at_unix         INTEGER,                                                     -- NULL = disabled / pending
    status                   INTEGER NOT NULL DEFAULT 0
                                CHECK (status IN (0, 1, 2)),                              -- 0=Enabled, 1=Disabled, 2=Failed
    created_at_unix          INTEGER NOT NULL,                                            -- UTC unix seconds
    bearer_token_hash        TEXT                                                         -- SHA-256 of HTTP trigger token; NULL for non-HTTP
);

CREATE INDEX IF NOT EXISTS idx_schedules_due
    ON schedules (status, next_run_at_unix)
    WHERE status = 0;

CREATE INDEX IF NOT EXISTS idx_schedules_project_alias
    ON schedules (project_alias);

-- ----------------------------------------------------------------------------
-- schedule_history table
-- ----------------------------------------------------------------------------
--
-- Append-only fire-attempt outcome ledger. Every Fire emits one row
-- (success / failure / skipped / rate-limited). `hades schedule history`
-- queries by schedule_id + time range; idx_schedule_history_lookup
-- supports both predicates with one composite index.
--
-- Retention: release track ships unbounded growth; the per-spec retention
-- policy is deferred to HADES design quality (operator-driven vacuum). No FK
-- back to schedules.id (history outlives the schedule — `hades day`
-- digest must surface fires for since-deleted routines).
--
-- Constraints:
--
--   - id INTEGER PRIMARY KEY AUTOINCREMENT: standard append-only PK.
--   - schedule_id TEXT NOT NULL: matches schedules.id at the
--                          application layer; no FK (forensic survival).
--   - fired_at_unix INTEGER NOT NULL: UTC unix seconds.
--   - outcome INTEGER NOT NULL CHECK (outcome IN (0,1,2,3)):
--                          0=Success, 1=Failed, 2=Skipped, 3=RateLimited.
--                          Skipped covers miss-policy=Skip + capa-firewall
--                          NotifyOnly paths; RateLimited covers
--                          token-bucket exhaustion (1 fire / 30s /
--                          project per Q9 C).
--   - reason TEXT NOT NULL DEFAULT '': human-readable failure / skip
--                          reason; empty for Success.
--   - cost_usd REAL NOT NULL DEFAULT 0: cost emitted from cost_ledger
--                          post-call (HADES design invariant integration).
--                          The Go-side rejects negative values.
--   - duration_ms INTEGER NOT NULL DEFAULT 0: end-to-end fire latency.
--                          The Go-side rejects negative values.

CREATE TABLE IF NOT EXISTS schedule_history (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    schedule_id   TEXT NOT NULL,
    fired_at_unix INTEGER NOT NULL,
    outcome       INTEGER NOT NULL CHECK (outcome IN (0, 1, 2, 3)),                       -- 0=Success, 1=Failed, 2=Skipped, 3=RateLimited
    reason        TEXT NOT NULL DEFAULT '',
    cost_usd      REAL NOT NULL DEFAULT 0,
    duration_ms   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_schedule_history_lookup
    ON schedule_history (schedule_id, fired_at_unix);
