// SPDX-License-Identifier: MIT
package safetynet

import (
	"context"
	"regexp"
	"strings"
)

type Severity string

const (
	SeverityHard Severity = "hard"

	SeveritySoft Severity = "soft"
)

type Commit struct {
	SHA     string
	Subject string
	Body    string
}

type CommitSource interface {
	Recent(ctx context.Context, n int) ([]Commit, error)
}

type Finding struct {
	CommitSHA string
	Rule      string
	Severity  Severity
	Detail    string
}

type Report struct {
	Findings    []Finding
	MaxSeverity Severity
}

type Drift struct {
	src  CommitSource
	emit Emitter
}

func NewDrift(src CommitSource, emit Emitter) *Drift { return &Drift{src: src, emit: emit} }

var (
	reConventional = regexp.MustCompile(`^(feat|fix|chore|docs|refactor|test|perf|build|ci|style|revert)(\([^)]+\))?: \S`)
	reClaude       = regexp.MustCompile(`(?i)co-authored-by.*claude|generated.{0,30}claude|generated.{0,30}ai`)
	reStub         = regexp.MustCompile(`(?i)todo:?\s*implement|panic\("not implemented|ErrNotImplementedPlan|fixme implement`)
	reTechDebt     = regexp.MustCompile(`(?i)tech[- ]debt|minor.*defer|revisit (in )?plan ?\d+`)
)

func (d *Drift) Validate(ctx context.Context, n int) (Report, error) {
	commits, err := d.src.Recent(ctx, n)
	if err != nil {
		return Report{}, err
	}
	rep := Report{}
	for _, c := range commits {
		text := c.Subject + "\n" + c.Body
		add := func(rule string, sev Severity, detail string) {
			rep.Findings = append(rep.Findings, Finding{
				CommitSHA: c.SHA, Rule: rule, Severity: sev, Detail: detail,
			})
			_ = d.emit.Emit(ctx, Event{
				Type: EventSubstrateDriftDetected,
				Payload: map[string]any{
					"commit_sha": c.SHA,
					"rule":       rule,
					"severity":   string(sev),
					"detail":     detail,
				},
			})
		}
		if reClaude.FindString(text) != "" {
			add("no-claude-attribution", SeverityHard, "Claude attribution detected")
		}

		subject := strings.TrimSpace(c.Subject)
		isAutoGenerated := strings.HasPrefix(subject, `Revert "`) ||
			strings.HasPrefix(subject, "Merge ")
		if !isAutoGenerated && !reConventional.MatchString(subject) {
			add("conventional-commit-subject", SeverityHard, c.Subject)
		}
		if reStub.FindString(text) != "" {
			add("no-stub-markers", SeverityHard, "stub marker in commit body")
		}
		if reTechDebt.FindString(text) != "" {
			add("no-tech-debt", SeveritySoft, "tech-debt marker in commit body")
		}
	}
	for _, f := range rep.Findings {
		if f.Severity == SeverityHard {
			rep.MaxSeverity = SeverityHard
			break
		}
		if f.Severity == SeveritySoft {
			rep.MaxSeverity = SeveritySoft
		}
	}
	return rep, nil
}
