#!/usr/bin/env bash
# SPDX-License-Identifier: MIT

set -euo pipefail

MODE="dry-run"
TARGET_DIR="."

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)
            MODE="dry-run"
            shift
            ;;
        --apply)
            MODE="apply"
            shift
            ;;
        --target-dir)
            if [ $# -lt 2 ]; then
                echo "FAIL: --target-dir requires an argument" >&2
                exit 2
            fi
            TARGET_DIR="$2"
            shift 2
            ;;
        --target-dir=*)
            TARGET_DIR="${1#--target-dir=}"
            shift
            ;;
        --help|-h)
            cat <<EOF
Usage: $0 [--dry-run|--apply] [--target-dir DIR]

Plan 15 Phase K Task K-1 — deterministic comment pre-pass.

  --dry-run          Report planned deletions (default; non-destructive).
  --apply            Modify files in place (DESTRUCTIVE; explicit flag required).
  --target-dir DIR   Limit scan to DIR (default: cwd).
  --help / -h        Show this usage.

Deletes 5 categories of rot from Go + Python source comments:
  1. bare "Plan N" task-context refs
  2. "v0.X.Y" release-marker refs
  3. "TODO ..." without owner (preserves "TODO(name [date]): ...")
  4. "added by claude" / "generated by" AI-attribution leaks
  5. "per spec/plan/see docs/superpowers/..." private-manifest pointers

Excludes ./vendor/* and */testdata/* (intentional fixture rot).
EOF
            exit 0
            ;;
        *)
            echo "FAIL: unknown arg: $1" >&2
            echo "Run '$0 --help' for usage." >&2
            exit 2
            ;;
    esac
done

if [ ! -d "$TARGET_DIR" ]; then
    echo "FAIL: --target-dir does not exist: $TARGET_DIR" >&2
    exit 2
fi


PATTERNS_GO=(
    '^[[:space:]]*//[[:space:]]*Plan [0-9]+([[:space:]].*)?$'
    '^[[:space:]]*//[[:space:]]*v0\.[0-9]+\.[0-9]+.*$'
    '^[[:space:]]*//[[:space:]]*TODO[[:space:]]+[^(].*$'
    '^[[:space:]]*//[[:space:]]*TODO:?[[:space:]]*$'
    '^[[:space:]]*//[[:space:]]*[Aa]dded by [Cc]laude.*$'
    '^[[:space:]]*//[[:space:]]*[Gg]enerated by .*$'
    '^[[:space:]]*//[[:space:]]*[Cc]reated by [Cc]laude.*$'
    '^[[:space:]]*//[[:space:]]*per spec docs/superpowers.*$'
    '^[[:space:]]*//[[:space:]]*per plan docs/superpowers.*$'
    '^[[:space:]]*//[[:space:]]*see docs/superpowers.*$'
)

PATTERNS_PY=(
    '^[[:space:]]*#[[:space:]]*Plan [0-9]+([[:space:]].*)?$'
    '^[[:space:]]*#[[:space:]]*v0\.[0-9]+\.[0-9]+.*$'
    '^[[:space:]]*#[[:space:]]*TODO[[:space:]]+[^(].*$'
    '^[[:space:]]*#[[:space:]]*TODO:?[[:space:]]*$'
    '^[[:space:]]*#[[:space:]]*[Aa]dded by [Cc]laude.*$'
    '^[[:space:]]*#[[:space:]]*[Gg]enerated by .*$'
    '^[[:space:]]*#[[:space:]]*[Cc]reated by [Cc]laude.*$'
    '^[[:space:]]*#[[:space:]]*per spec docs/superpowers.*$'
    '^[[:space:]]*#[[:space:]]*per plan docs/superpowers.*$'
    '^[[:space:]]*#[[:space:]]*see docs/superpowers.*$'
)


GO_FILES_TMP="$(mktemp)"
PY_FILES_TMP="$(mktemp)"
REPORT_FILE="$(mktemp)"
trap 'rm -f "$GO_FILES_TMP" "$PY_FILES_TMP" "$REPORT_FILE"' EXIT

find "$TARGET_DIR" \
    \( -path '*/vendor' -o -path '*/vendor/*' \
       -o -path '*/testdata' -o -path '*/testdata/*' \
       -o -path '*/.git' -o -path '*/.git/*' \
    \) -prune -o \
    -type f -name '*.go' -print0 > "$GO_FILES_TMP"

find "$TARGET_DIR" \
    \( -path '*/vendor' -o -path '*/vendor/*' \
       -o -path '*/testdata' -o -path '*/testdata/*' \
       -o -path '*/.git' -o -path '*/.git/*' \
       -o -path '*/node_modules' -o -path '*/node_modules/*' \
       -o -path '*/__pycache__' -o -path '*/__pycache__/*' \
       -o -path '*/.venv' -o -path '*/.venv/*' \
    \) -prune -o \
    -type f -name '*.py' -print0 > "$PY_FILES_TMP"


run_grep_for_patterns() {
    local file="$1"
    shift
    local pattern
    for pattern in "$@"; do
        grep -nE "$pattern" "$file" 2>/dev/null \
            | sed -e "s|^|${file}:|" >> "$REPORT_FILE" || true
    done
}

while IFS= read -r -d '' file; do
    run_grep_for_patterns "$file" "${PATTERNS_GO[@]}"
done < "$GO_FILES_TMP"

while IFS= read -r -d '' file; do
    run_grep_for_patterns "$file" "${PATTERNS_PY[@]}"
done < "$PY_FILES_TMP"

sort -u "$REPORT_FILE" -o "$REPORT_FILE"

TOTAL_DELETIONS="$(wc -l < "$REPORT_FILE" | tr -d '[:space:]')"

echo "Phase K K-1 comment_prepass — mode: ${MODE}"
echo "Target dir: ${TARGET_DIR}"
echo "Planned deletions: ${TOTAL_DELETIONS} lines across Go + Python source"
echo ""
echo "Report (first 50 lines):"
head -50 "$REPORT_FILE" || true

if [ "$MODE" = "dry-run" ]; then
    echo ""
    echo "DRY-RUN: no files modified. Re-run with --apply to delete."
    exit 0
fi


apply_to_file() {
    local file="$1"
    shift
    local combined=""
    local pattern
    for pattern in "$@"; do
        if [ -z "$combined" ]; then
            combined="$pattern"
        else
            combined="${combined}|${pattern}"
        fi
    done
    local tmp
    tmp="$(mktemp "${file}.prepass.XXXXXX")"
    awk -v re="$combined" '$0 ~ re { next } { print }' "$file" > "$tmp"
    if ! mv "$tmp" "$file"; then
        rm -f "$tmp"
        echo "FAIL: could not write $file" >&2
        return 1
    fi
}

echo ""
echo "APPLY: deleting rot patterns..."

while IFS= read -r -d '' file; do
    apply_to_file "$file" "${PATTERNS_GO[@]}"
done < "$GO_FILES_TMP"

while IFS= read -r -d '' file; do
    apply_to_file "$file" "${PATTERNS_PY[@]}"
done < "$PY_FILES_TMP"

echo "OK: ${TOTAL_DELETIONS} lines deleted across Go + Python source"
echo "    Next: run K-2 per-package fan-out for KEEP/REWRITE judgment calls"
exit 0
