#!/usr/bin/env bash
# Purpose: insert `SPDX-License-Identifier: MIT` at the top of every
#  .go         -> // SPDX-License-Identifier: MIT
#  .py,.sh    -> # SPDX-License-Identifier: MIT

set -euo pipefail

SPDX_LINE_GO="// SPDX-License-Identifier: MIT"
SPDX_LINE_HASH="# SPDX-License-Identifier: MIT"

DRY_RUN=0
INCLUDE_TESTS=0
VERBOSE=0

usage() {
    cat <<'EOF'
Usage: insert_spdx_headers.sh [--dry-run] [--verbose] [--include-tests] [--help]

Inserts SPDX-License-Identifier: MIT into every .go/.py/.sh production file
(idempotent; re-runs produce zero modifications).

Flags:
  --dry-run        Report files that would be modified; do not write.
  --verbose        Print each modified path (one per line).
  --include-tests  Include _test.go files (default: excluded).
  --help, -h       Show this help and exit.

inv-zen-287 — every production .go/.py/.sh file has SPDX-MIT header.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1 ;;
        --include-tests) INCLUDE_TESTS=1 ;;
        --verbose) VERBOSE=1 ;;
        --help|-h) usage; exit 0 ;;
        *)
            echo "ERROR: unknown flag: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
    shift
done

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "${REPO_ROOT}"

CANDIDATES="$(find . \
    -path './vendor' -prune -o \
    -path './.git' -prune -o \
    -path './.claire' -prune -o \
    -path './node_modules' -prune -o \
    -name '.venv' -prune -o \
    -name 'venv' -prune -o \
    -name '.tox' -prune -o \
    -name '.mypy_cache' -prune -o \
    -name '.pytest_cache' -prune -o \
    -name '__pycache__' -prune -o \
    -path './bin' -prune -o \
    -path './dist' -prune -o \
    -path './build' -prune -o \
    -path './private-tier1-module' -prune -o \
    \( -name '*.go' -o -name '*.py' -o -name '*.sh' \) -type f -print)"

CANDIDATES="$(printf '%s\n' "${CANDIDATES}" \
    | grep -v '/vendor/' \
    | grep -v '/\.git/' \
    | grep -v '/\.claire/' \
    | grep -v '/node_modules/' \
    | grep -v '/\.venv/' \
    | grep -v '/venv/' \
    | grep -v '/\.tox/' \
    | grep -v '/\.mypy_cache/' \
    | grep -v '/\.pytest_cache/' \
    | grep -v '/__pycache__/' \
    | grep -v '/private-tier1-module/' \
    || true)"

# Filter generated files (heuristic: "Code generated by... DO NOT EDIT"
is_generated() {
    head -100 "$1" 2>/dev/null | grep -qE '^(\/\/|#) Code generated by'
}

has_mit_spdx() {
    head -10 "$1" 2>/dev/null | grep -qE 'SPDX-License-Identifier:[[:space:]]*MIT'
}

has_nonmit_spdx() {
    # True when file has SPDX-License-Identifier but value is NOT MIT
    # (e.g., Apache-2.0). policy these MUST be rewritten to MIT.
    head -10 "$1" 2>/dev/null | grep -q 'SPDX-License-Identifier' \
        && ! head -10 "$1" 2>/dev/null | grep -qE 'SPDX-License-Identifier:[[:space:]]*MIT'
}

is_test_file() {
    case "$1" in
        *_test.go) return 0 ;;
        *) return 1 ;;
    esac
}

FILES_TO_PROCESS=()        # files without any SPDX (need insertion)
FILES_TO_REWRITE=()        # files with non-MIT SPDX (need identifier rewrite)
while IFS= read -r f; do
    [ -z "${f}" ] && continue
    if is_generated "${f}"; then
        continue
    fi
    if has_mit_spdx "${f}"; then
        continue
    fi
    if has_nonmit_spdx "${f}"; then
        FILES_TO_REWRITE+=("${f}")
        continue
    fi
    if is_test_file "${f}" && [ "${INCLUDE_TESTS}" -eq 0 ]; then
        continue
    fi
    FILES_TO_PROCESS+=("${f}")
done <<<"${CANDIDATES}"

if [ "${DRY_RUN}" -eq 1 ]; then
    total=$(( ${#FILES_TO_PROCESS[@]} + ${#FILES_TO_REWRITE[@]} ))
    echo "Dry run: ${total} files would be modified (${#FILES_TO_PROCESS[@]} insert + ${#FILES_TO_REWRITE[@]} non-MIT rewrite)."
    if [ "${VERBOSE}" -eq 1 ]; then
        if [ "${#FILES_TO_PROCESS[@]}" -gt 0 ]; then
            echo "Insert SPDX-MIT header:"
            for f in "${FILES_TO_PROCESS[@]}"; do
                printf '  + %s\n' "${f}"
            done
        fi
        if [ "${#FILES_TO_REWRITE[@]}" -gt 0 ]; then
            echo "Rewrite non-MIT SPDX -> MIT:"
            for f in "${FILES_TO_REWRITE[@]}"; do
                printf '  ~ %s\n' "${f}"
            done
        fi
    fi
    exit 0
fi

insert_header() {
    local file="$1"
    local first_line spdx_line
    first_line="$(head -1 "${file}" 2>/dev/null || true)"

    case "${file}" in
        *.go) spdx_line="${SPDX_LINE_GO}" ;;
        *.py|*.sh) spdx_line="${SPDX_LINE_HASH}" ;;
        *)
            return 0
            ;;
    esac

    local tmp
    tmp="$(mktemp)"

    case "${file}" in
        *.go)
            if [[ "${first_line}" == //go:build* ]]; then
                {
                    printf '%s\n' "${first_line}"
                    printf '%s\n' "${spdx_line}"
                    tail -n +2 "${file}"
                } > "${tmp}"
            else
                {
                    printf '%s\n' "${spdx_line}"
                    cat "${file}"
                } > "${tmp}"
            fi
            ;;
        *.py|*.sh)
            if [[ "${first_line}" == \#!* ]]; then
                {
                    printf '%s\n' "${first_line}"
                    printf '%s\n' "${spdx_line}"
                    tail -n +2 "${file}"
                } > "${tmp}"
            else
                {
                    printf '%s\n' "${spdx_line}"
                    cat "${file}"
                } > "${tmp}"
            fi
            ;;
    esac

    if command -v stat >/dev/null 2>&1; then
        local mode
        mode="$(stat -f '%Lp' "${file}" 2>/dev/null || stat -c '%a' "${file}" 2>/dev/null || echo "")"
        if [ -n "${mode}" ]; then
            chmod "${mode}" "${tmp}"
        fi
    fi

    mv "${tmp}" "${file}"

    if [ "${VERBOSE}" -eq 1 ]; then
        echo "  + ${file}"
    fi
}

rewrite_nonmit_spdx() {
    # Rewrites the existing `SPDX-License-Identifier: <X>` line to
    # `SPDX-License-Identifier: MIT` within the first 10 lines.
    local file="$1"
    local tmp
    tmp="$(mktemp)"
    awk '
        NR <= 10 && /SPDX-License-Identifier:/ {
            sub(/SPDX-License-Identifier:[[:space:]]*[^[:space:]]+/, "SPDX-License-Identifier: MIT")
            print
            next
        }
        { print }
    ' "${file}" > "${tmp}"

    if command -v stat >/dev/null 2>&1; then
        local mode
        mode="$(stat -f '%Lp' "${file}" 2>/dev/null || stat -c '%a' "${file}" 2>/dev/null || echo "")"
        if [ -n "${mode}" ]; then
            chmod "${mode}" "${tmp}"
        fi
    fi
    mv "${tmp}" "${file}"
}

COUNT_INSERT=0
COUNT_REWRITE=0
GO_FILES_MODIFIED=()
if [ "${#FILES_TO_PROCESS[@]}" -gt 0 ]; then
    for f in "${FILES_TO_PROCESS[@]}"; do
        insert_header "${f}"
        COUNT_INSERT=$((COUNT_INSERT + 1))
        case "${f}" in
            *.go) GO_FILES_MODIFIED+=("${f}") ;;
        esac
    done
fi
if [ "${#FILES_TO_REWRITE[@]}" -gt 0 ]; then
    for f in "${FILES_TO_REWRITE[@]}"; do
        rewrite_nonmit_spdx "${f}"
        COUNT_REWRITE=$((COUNT_REWRITE + 1))
        if [ "${VERBOSE}" -eq 1 ]; then
            echo "  ~ ${f}"
        fi
        case "${f}" in
            *.go) GO_FILES_MODIFIED+=("${f}") ;;
        esac
    done
fi

if [ "${#GO_FILES_MODIFIED[@]}" -gt 0 ] && command -v gofmt >/dev/null 2>&1; then
    gofmt -w "${GO_FILES_MODIFIED[@]}"
fi

TOTAL=$((COUNT_INSERT + COUNT_REWRITE))
echo "Inserted SPDX-License-Identifier: MIT header into ${COUNT_INSERT} files; rewrote non-MIT SPDX in ${COUNT_REWRITE} files (total: ${TOTAL})."
exit 0
