#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#      copyright per sub-decisión 15-1). Verified inline (sentinel grep).
#   inv-zen-286   LICENSE present + MIT canonical + 'Ika el Zur' copyright
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

echo "================================================================="
echo "  verify_license_compliance.sh — Plan 15 Phase C-8 (MIT, W4C)"
echo "================================================================="

echo "-> Gate 1: LICENSE canonical MIT content (inv-zen-286)..."
if [ ! -f LICENSE ]; then
    echo "  FAIL: LICENSE absent at repo root (inv-zen-286)" >&2
    exit 1
fi
if ! grep -q "MIT License" LICENSE; then
    echo "  FAIL: LICENSE missing 'MIT License' marker (decisión 15)" >&2
    if grep -q "Apache License" LICENSE; then
        echo "        LICENSE contains Apache markers; decisión 15 mandates MIT" >&2
    fi
    exit 1
fi
if ! grep -q "Copyright (c) 2026 Ika el Zur" LICENSE; then
    echo "  FAIL: LICENSE missing canonical Copyright 'Copyright (c) 2026 Ika el Zur' (sub-15-1)" >&2
    exit 1
fi
if ! grep -q "Permission is hereby granted" LICENSE; then
    echo "  FAIL: LICENSE missing 'Permission is hereby granted' marker" >&2
    exit 1
fi
if ! grep -q 'THE SOFTWARE IS PROVIDED "AS IS"' LICENSE; then
    echo "  FAIL: LICENSE missing 'AS IS' marker" >&2
    exit 1
fi
echo "  OK: LICENSE MIT canonical + 'Ika el Zur' copyright verified"

echo "-> Gate 2: per-file SPDX-MIT headers on production code (inv-zen-287)..."
MISSING_SPDX_COUNT=0
MISSING_SPDX_SAMPLE=()
while IFS= read -r f; do
    [ -z "$f" ] && continue
    case "$f" in
        ./vendor/*|./.git/*|./node_modules/*|./.venv/*|./venv/*|./.tox/*|./.mypy_cache/*|./.pytest_cache/*|./__pycache__/*|./bin/*|./dist/*|./build/*|./private-tier1-module/*)
            continue
            ;;
    esac
    case "$f" in
        *_test.go|*/testdata/*)
            continue
            ;;
    esac
    if head -c 4096 "$f" 2>/dev/null | grep -q "Code generated by"; then
        continue
    fi
    if ! head -10 "$f" 2>/dev/null | grep -q "SPDX-License-Identifier:[[:space:]]*MIT"; then
        MISSING_SPDX_COUNT=$((MISSING_SPDX_COUNT + 1))
        if [ "$MISSING_SPDX_COUNT" -le 10 ]; then
            MISSING_SPDX_SAMPLE+=("$f")
        fi
    fi
done < <(find . \
    \( -path "./vendor" -o -path "./.git" -o -path "./node_modules" -o -name ".venv" -o -name "venv" -o -name ".tox" -o -name ".mypy_cache" -o -name ".pytest_cache" -o -name "__pycache__" -o -path "./bin" -o -path "./dist" -o -path "./build" -o -path "./private-tier1-module" \) -prune \
    -o \( -name "*.go" -o -name "*.py" -o -name "*.sh" \) -type f -print 2>/dev/null)

if [ "$MISSING_SPDX_COUNT" -gt 0 ]; then
    echo "  FAIL: $MISSING_SPDX_COUNT production files missing SPDX-MIT header (inv-zen-287)" >&2
    for s in "${MISSING_SPDX_SAMPLE[@]}"; do
        echo "    $s" >&2
    done
    if [ "$MISSING_SPDX_COUNT" -gt 10 ]; then
        echo "    ... and $((MISSING_SPDX_COUNT - 10)) more" >&2
    fi
    echo "    Remediation: scripts/insert_spdx_headers.sh" >&2
    exit 2
fi
echo "  OK: all production .go/.py/.sh files declare SPDX-License-Identifier: MIT"

echo "-> Gate 3: 4-redundant disclosure surface composition (Phase A-6; inv-zen-174 + inv-zen-290)..."
if [ ! -x "scripts/verify_license_disclosure.sh" ]; then
    echo "  FAIL: Phase A-6 verify_license_disclosure.sh missing or not executable" >&2
    exit 3
fi
if ! bash scripts/verify_license_disclosure.sh; then
    echo "  FAIL: Phase A-6 surface scan reported inconsistency (inv-zen-174 + inv-zen-290)" >&2
    exit 3
fi
echo "  OK: 4-redundant MIT surfaces consistent (composition contract)"

echo "-> Gate 4: NOTICE optional sentinel check (W4C C-3 scope; decisión 15)..."
if [ ! -f NOTICE ]; then
    echo "  OK: NOTICE absent (MIT does not require NOTICE; decisión 15 plan default)"
else
    NOTICE_FAIL=0
    for sentinel in "HADES" "MIT License" "Apache-2.0" "THIRD_PARTY_LICENSES.md"; do
        if ! grep -qF "$sentinel" NOTICE; then
            echo "  FAIL: NOTICE missing sentinel: '$sentinel'" >&2
            NOTICE_FAIL=1
        fi
    done
    if [ "$NOTICE_FAIL" -ne 0 ]; then
        echo "    Remediation: see Plan 15 Phase C-3 W4C deliverable for canonical content." >&2
        exit 4
    fi
    echo "  OK: NOTICE present + all 4 sentinels verified"
fi

echo ""
echo "================================================================="
echo "  ALL LICENSE-COMPLIANCE GATES PASSED (MIT-canonical per decisión 15)"
echo "    inv-zen-286  LICENSE MIT canonical + 'Ika el Zur' copyright"
echo "    inv-zen-287  SPDX-MIT headers on production code"
echo "    inv-zen-174  4-redundant MIT disclosure surfaces consistent"
echo "    inv-zen-290  composition contract (A-6 + C-4 + C-3 + LICENSE)"
echo "================================================================="
exit 0
