#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
set -euo pipefail

PATTERNS=(
    "^[[:space:]]*//[[:space:]]*Plan [0-9][0-9]*"
    "^[[:space:]]*//[[:space:]]*v0\.[0-9]+\.[0-9]+"
    "^[[:space:]]*//[[:space:]]*TODO[[:space:]]+[^(]"
    "^[[:space:]]*//[[:space:]]*(added by claude|generated by)"
    "^[[:space:]]*//[[:space:]]*(per spec|per plan|see) docs/superpowers"
)
PATTERNS_PY=(
    "^[[:space:]]*#[[:space:]]*Plan [0-9][0-9]*"
    "^[[:space:]]*#[[:space:]]*v0\.[0-9]+\.[0-9]+"
    "^[[:space:]]*#[[:space:]]*TODO[[:space:]]+[^(]"
    "^[[:space:]]*#[[:space:]]*(added by claude|generated by)"
    "^[[:space:]]*#[[:space:]]*(per spec|per plan|see) docs/superpowers"
)

TOTAL=0
SCAN_DIRS_GO=()
for d in internal cmd; do
    [[ -d "$d" ]] && SCAN_DIRS_GO+=("$d")
done
SCAN_DIRS_PY=()
[[ -d plugin ]] && SCAN_DIRS_PY+=(plugin)

if [[ ${#SCAN_DIRS_GO[@]} -gt 0 ]]; then
    for PATTERN in "${PATTERNS[@]}"; do
        HITS="$(grep -rEn "$PATTERN" \
            --include='*.go' \
            --exclude-dir=vendor \
            --exclude-dir=testdata \
            --exclude-dir=.venv \
            --exclude-dir=venv \
            --exclude-dir=.tox \
            --exclude-dir=.mypy_cache \
            --exclude-dir=.pytest_cache \
            --exclude-dir=__pycache__ \
            "${SCAN_DIRS_GO[@]}" 2>/dev/null || true)"
        if [[ -n "$HITS" ]]; then
            echo "FAIL: Go rot pattern '$PATTERN' found:"
            echo "$HITS"
            TOTAL=$((TOTAL + $(echo "$HITS" | wc -l)))
        fi
    done
fi
if [[ ${#SCAN_DIRS_PY[@]} -gt 0 ]]; then
    for PATTERN in "${PATTERNS_PY[@]}"; do
        HITS="$(grep -rEn "$PATTERN" \
            --include='*.py' \
            --exclude-dir=vendor \
            --exclude-dir=testdata \
            --exclude-dir=.venv \
            --exclude-dir=venv \
            --exclude-dir=.tox \
            --exclude-dir=.mypy_cache \
            --exclude-dir=.pytest_cache \
            --exclude-dir=__pycache__ \
            "${SCAN_DIRS_PY[@]}" 2>/dev/null || true)"
        if [[ -n "$HITS" ]]; then
            echo "FAIL: Python rot pattern '$PATTERN' found:"
            echo "$HITS"
            TOTAL=$((TOTAL + $(echo "$HITS" | wc -l)))
        fi
    done
fi

if [[ "$TOTAL" -gt 0 ]]; then
    echo ""
    echo "FAIL: ${TOTAL} task-context-rot comment lines re-introduced"
    echo "      Per Plan 15 K-1/K-9 anti-recurrence: delete or convert to actionable Issue."
    echo "      Auto-fix: bash scripts/comment_prepass.sh --apply"
    exit 1
fi

echo "OK: zero task-context-rot patterns in Go + Python source"
exit 0
