# SPDX-License-Identifier: MIT
"""/hades:openspec-archive handler — Three-tier review (routine/attention/decision) and merge.

Port from CC-format plugin/hades/commands/openspec-archive.md workflow logic.
"""

from __future__ import annotations

_PROMPT = """# HADES /openspec-archive — Archive phase for {feature_name}

Per spec §3.3 (Modo C híbrido) via HADES:

## 1. Trigger archive via daemon

```bash
SWARM_ID=$(curl --unix-socket /tmp/hades-system.sock -s \\
                "http://unix/v1/swarms?feature={feature_name}" \\
                | jq -r '.swarms[0].id')

# pending endpoint registration: swarm archive (POST) per spec §3.3 archive phase awaits hades migrate
curl --unix-socket /tmp/hades-system.sock \\
     -X POST \\
     "http://unix/v1/swarms/$SWARM_ID/archive"
```

Daemon's audit MCP produces archive briefing JSON.

## 2. Render briefing in three tiers

```
# Archive briefing for {feature_name}
## TIER-ROUTINE (auto-mergeable, single approval)
- Task <id>: <title> — codegen passed, tests green, audit signal clean

## TIER-ATTENTION (review-only, no decision required)
- Task <id>: <title>: <attention reason: e.g., low-confidence audit signal>

## TIER-DECISION (operator call required)
- Task <id>: <title>: <decision reason: e.g., cross-task conflict / audit flag>
  Options:
  (A) Merge as-is (override audit)
  (B) Reject + re-run task
  (C) Manual fix + merge
```

## 3. Operator confirms each tier-decision item

For each TIER-DECISION row, operator answers A/B/C. Capture decisions.

## 4. Apply deltas to openspec/specs/

Daemon applies deltas from `openspec/changes/{feature_name}/deltas/` to `openspec/specs/<area>.md` files.

## 5. Commit with trailers

```
git commit -m "feat({feature_name}): <subject>

<body>

HADES-Trace-Id: <trace-id>
HADES-Provider: <provider>
HADES-Audit-Passed: yes
"
```

## 6. NEVER add Claude/Anthropic/AI attribution (inv-hades-004)

the release design substrate hook (`hooks/llm_handlers.py` pre_llm_call callback) regex-rejects commit messages containing:
- `Co-Authored-By: prohibited assistant`
- `Generated with prohibited assistant`
- `Generated by prohibited assistant`
- `Anthropic`

## 7. Cleanup worktrees + branches

```bash
# pending endpoint registration: swarm cleanup per cleanup-policy.toml awaits hades migrate
curl --unix-socket /tmp/hades-system.sock \\
     -X POST \\
     "http://unix/v1/swarms/$SWARM_ID/cleanup"
```

Per cleanup-policy.toml.

## Cross-references

- spec §3.3 archive phase
- inv-hades-004 NO Claude attribution
- the release design MergeEngine (winner selection per spec §4.4)
- /hades:openspec-apply (precedent step)
"""

_PROMPT_NO_FEATURE = """HADES: feature name required for openspec-archive
  /hades:openspec-archive requires a feature name to identify the swarm to archive.
  → Run /hades:openspec-apply <feature-name> first to complete the apply phase, then invoke /hades:openspec-archive <feature-name>
"""


def openspec_archive_handler(raw_args: str) -> str | None:
    """/hades:openspec-archive handler. raw_args: feature_name (required)."""
    feature_name = raw_args.strip()
    if not feature_name:
        return _PROMPT_NO_FEATURE
    return _PROMPT.format(feature_name=feature_name)
